### ISSUE TITLE
Purity shows NA with raw files as input

### ISSUE THREAD

**Issue by jmcalist** [Nesvilab/FragPipe#559] opened 2021-12-09 17:55 UTC
- Describe the issue or question:
Hello,
Thank you for offering wonderful software! We were doing a TMT run and it seems to have stopped with 1 remaining task, with a message of can't find the reference channel. I attached a screenshot with the reference channel labeled as pool in the annotation file, and the Ref sample tag indicated as pool. I am sure I am missing something, please let me know :) 

Thanks so much!

All the best,

Jason

- Upload your log file
[log_2021-12-09_12-49-38.txt](https://github.com/Nesvilab/FragPipe/files/7687336/log_2021-12-09_12-49-38.txt)

(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
![Fragpipe TMT Ref sample pool](https://user-images.githubusercontent.com/72038445/145449171-cd56b782-0dc7-4d72-b940-432be04d1d41.png)

**Comment by prvst** [comment] 2021-12-09 20:46
Hi Jason, did you run the isobaric quantification step?

**Comment by jmcalist** [comment] 2021-12-09 20:56
Hi Felipe,

Thank you so much for your reply! I believe I did, but it is my first time trying TMT with Fragpipe so I may have missed it, does it show up in the logfile?

Thanks again!

All the best,

Jason
________________________________

**Comment by prvst** [comment] 2021-12-09 20:58
It looks like you went from the filter to TMT-Integrator. Why do you give it another shot, make sure you have the TMT quantification checked.

**Comment by sarah-haynes** [comment] 2021-12-09 21:05
Hi Jason, we always recommend loading one of the provided workflows (probably `TMT16` in this case), then **only** modifying settings as needed.

**Comment by jmcalist** [comment] 2021-12-09 21:26
Thank you both so much! I believed I used the provided workflow for TMT-16, I did not intend to change other settings, any changes would have been unintentional

In the attached screenshots, are these settings correct:

  *   Run TMT integrator is checked
  *   Should Run MS1 Quant be checked?

Felipe, I did not find where to check TMT quantification, if you could send a screenshot I would really appreciate it :)

I did not upload the annotation files in the screenshots, but we have 8 samples, each with 15 TMT labels and one common channel (pool). Would I therefore have 8 different annotation files, each with the names of the 15 samples, and the common channel (pool)

Thank you again for your help, I hope my replies and questions above make sense 🙂

All the best,

Jason




Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jmcalist** [comment] 2021-12-09 21:42
Hi Sarah,

Thank you so much, I will work on setting this up again tomorrow and let you know

Thanks so much for your assistance and patience 🙂

All the best,

Jason
________________________________

**Comment by jmcalist** [comment] 2021-12-14 15:18
Hi Sarah,

Thank you so much for your assistance, I ran the TMT tutorial with the provided files and it worked great, reached Done in 14 minutes. When I ran it with my files it stops at the TMT Integrator (see attached log file).

I see that the tmt-report file is empty, so I attached the annotation files here as well for each plex to make sure that they are setup properly. These two annotation files are each in separate folders (see screenshot), each of these 2 folders holds raw data and an annotation file for each plex.

I hope this is helpful and makes sense, thank you so much for any help you can provide 🙂

All the best,

Jason
________________________________

**Comment by sarah-haynes** [comment] 2021-12-14 16:35
Hi Jason, can you try adding the attachments again? You could also upload the entire experiment/directory here and I'll try to run it: https://www.dropbox.com/request/8sHqgrr4ArC2oh2SuL6G

**Comment by jmcalist** [comment] 2021-12-14 16:54
Thanks Sarah, here are the attachments, I had sent the last message through our University email (Outlook) and so the attachments may not have made it to you, hopefully these work

I will also upload the files, thank you so much for the offer to run it, very kind! 

[log_2021-12-13_11-34-55.txt](https://github.com/Nesvilab/FragPipe/files/7713350/log_2021-12-13_11-34-55.txt)
[annotation.txt](https://github.com/Nesvilab/FragPipe/files/7713354/annotation.txt)
[annotation.txt](https://github.com/Nesvilab/FragPipe/files/7713355/annotation.txt)
![Screenshot 2021-12-14 101558](https://user-images.githubusercontent.com/72038445/146042889-cecd5524-d5e0-4dbf-bc3c-4a7fe634284d.png)

**Comment by sarah-haynes** [comment] 2021-12-17 14:39
Hi Jason, I can indeed reproduce the issue, we are looking into it. Thanks for your patience!

--Sarah

**Comment by sarah-haynes** [comment] 2021-12-22 19:49
Hi Jason, could you try [converting your files to mzML](https://fragpipe.nesvilab.org/docs/tutorial_convert.html) for the time being? We think there may be something with the .raw files that is causing an issue with the purity calculation, we will investigate further, but please let me know if that works for you in the mean time.

**Comment by jmcalist** [comment] 2021-12-23 18:59
Hi Sarah,

Yes, I can certainly do that, thank you so much for all of your assistance! This team's prompt responses helping users with your software is a massive advantage of Fragpipe! 

Thanks again to you all and have a happy and safe Holiday Season!

**Comment by fcyu** [comment] 2022-04-12 19:59
Close this issue because Philosopher no longer supports raw files.

**Closed by fcyu** 2022-04-12 19:59 UTC
Labels: Philosopher
