### ISSUE TITLE
Uniprot fasta download

### ISSUE THREAD

**Issue by mwfoster** [Nesvilab/FragPipe#739] opened 2022-06-28 23:30 UTC
The fasta download feature is not working correctly possibly due to update of Uniprot. The fasta file has this error in the header: {"url":"http://rest.uniprot.org/uniprotkb/query=reviewed:yes%20AND%20proteome:UP000002311&amp;format=fasta&amp;include=no","messages":["The 'accession' value has invalid format. It should be a valid UniProtKB accession"]}

**Comment by fcyu** [comment] 2022-06-28 23:59
Hi @mwfoster ,

I can't reproduce the error:
```
19:58:34 INFO : Executing: G:\bin\philosopher_v4.2.2_windows_amd64\philosopher.exe workspace --init --nocheck --temp C:\Users\yufe\AppData\Local\Temp\322d51b7-9856-4f3f-8aed-4164fd7a0bd7
19:58:34 INFO : Process output: 
19:58:34 INFO : Monitoring directory for file changes: G:\dev
19:58:34 INFO : Executing: G:\bin\philosopher_v4.2.2_windows_amd64\philosopher.exe database --reviewed --contam --contamprefix --id UP000002311
19:58:35 INFO : Process output: 
19:58:35 INFO : Executing: G:\bin\philosopher_v4.2.2_windows_amd64\philosopher.exe workspace --clean --nocheck
19:58:35 INFO : Process output: 
19:58:35 INFO : Detected new or changed file: 2022-06-28-decoys-reviewed-contam-UP000002311.fas
19:58:35 INFO : Extension: [fas]
19:58:35 INFO : Is regular file: true; Is not inside .meta folder: true; Extension starts with .fa: true
```

Best,

Fengchao

**Comment by mwfoster** [comment] 2022-06-29 00:26
Can you confirm that the size of the file is correct? I get the same message but the file only contains the contaminants. Thanks, Matt

**Comment by fcyu** [comment] 2022-06-29 00:34
Hi Matt,

You are right! The fasta file is small and there are only contaminant proteins. Felipe @prvst , can you take a look?

Also, it seems that Philosopher does not report any errors if something is wrong in some modules. Here (https://github.com/Nesvilab/FragPipe/issues/562) is another example. I don't think it is a good practice to suppress the errors when something is going wrong.

Best,

Fengchao

**Comment by prvst** [comment] 2022-06-29 02:31
Hi Matt. I can reproduce your error. According to the message from Philosopher, the end point is not valid anymore. The UniProt team just updated their code base and the website, and they added a lot of changes. Unfortunately, their changes alter the REST API, which is how we fetch the data. I'll take a look at the new documentation and try to have the database working by tomorrow.

**Comment by fcyu** [comment] 2022-07-01 17:39
Fixed in https://github.com/Nesvilab/philosopher/releases/tag/v4.3.0

**Closed** 2022-07-01 17:39 UTC
Labels: Philosopher
