### ISSUE TITLE
easyPQP FP20 specific? crash

### ISSUE THREAD

**Issue by KlemensFroehlich** [Nesvilab/FragPipe#1275] opened 2023-10-05 14:31 UTC
Dear Developers,

I wanted to repeat a standard analysis in our lab with the latest FP Version (V20):
Analysis of the lymphnode ecoli dataset (which was also used in: "Analysis of DIA proteomics data using MSFragger-DIA and FragPipe computational platform" )
I run the analysis with the standard setting of DIA Speclib Quant and use only the 92 main samples for library building, so no DDA or GPF files.

In FP19.1 the files ran through on my local workstation (16 threads, 64GB ram). I am currently repeating the analysis to make sure that nothing changed in eg my python installation for the easypqp
But with FP20 I am running into problems, both using my local workstation but also with our linux server.

Please find attached the log file of my workstation.

[log_2023-10-04_22-51-54.txt](https://github.com/Nesvilab/FragPipe/files/12819552/log_2023-10-04_22-51-54.txt)

Thank you very much for your continued support and the great tools you provide!

Best, Klemens

**Comment by fcyu** [comment] 2023-10-05 14:51
Hi Klemens,

It seems to be related to a bug caused by 0 ID pep.xml. Could you upgrade the EasyPQP to the latest version and try again?

Thanks,

Fengchao

**Comment by fcyu** [comment] 2023-10-05 17:38
Hi Klemens,

Thanks for the prompt reply. I guess the bug was not fixed entirely. I pushed a commit, and can you have a try?

You need to uninstall and reinstall the new EasyPQP using the command
```shell
pip uninstall easypqp -y
pip install git+https://github.com/Nesvilab/easypqp.git@master
```

I am running the new version to test it, but it might take a while since the dataset is quite large.

Best,

Fengchao

**Comment by KlemensFroehlich** [comment] 2023-10-05 18:15
Hi Fengchao,

I uninstalled easypqp and installed the git master branch as instructed. I am running V20 now again. V19.1 did succesfully run through btw!
Will get back to you tomorrow. As you said, it is quite the dataset :)

Thanks already and have a great day!

Best Klemens

**Comment by KlemensFroehlich** [comment] 2023-10-06 07:49
hi Fengchao
The problem persists with exactly the same error. Did it run through on your machine?
Best, Klemens

**Comment by fcyu** [comment] 2023-10-06 13:09
Hi Klemens,

It finished without any error on my side. Maybe we were using different parameters or fasta files. 

Could you share your files, including interact-*pep.xml, fasta, and workflow files, with us? Here is the link to upload: https://www.dropbox.com/request/rIcVSUdgb11ln4fwFSUF

Thanks,

Fengchao

**Comment by KlemensFroehlich** [comment] 2023-10-06 14:41
Hi Fengchao
Then let me retry the easypqp reinstallation. Maybe something did not work there for me.
Best Klemens

**Comment by KlemensFroehlich** [comment] 2023-10-09 11:03
hi Fengchao
It was indeed a problem with my python installation. I totally forgot that FragPipe requires 3.9 and I am using a newer version for tensorflow etc and of course I installed the git easypqp for my later python version and not for the one specified in FragPipe.

Installing easypqp from git with the 3.9 installation specified in FragPipe solved the problem!

Thank you very much for the immediate fix 
Best Klemens

**Comment by fcyu** [comment] 2023-10-09 13:05
Hi Klemens,

Thank you for the update. Then, I will close this issue.

Best.

Fengchao

**Closed by fcyu** 2023-10-09 13:05 UTC

**Comment by jossmi** [comment] 2023-11-10 19:04
Hi Fengchao, I ran into this same error and tried the command you posted. the uninstall command worked, but I got a bug when I tried to run the install git command. See below for the error I got in the terminal. Any ideas?

C:\Python>python.exe -m pip uninstall easypqp -y
Found existing installation: easypqp 0.1.40
Uninstalling easypqp-0.1.40:
  Successfully uninstalled easypqp-0.1.40

C:\Python>python.exe -m pip install git+https://github.com/Nesvilab/easypqp.git@master
Collecting git+https://github.com/Nesvilab/easypqp.git@master
  Cloning https://github.com/Nesvilab/easypqp.git (to revision master) to c:\users\peaks\appdata\local\temp\pip-req-build-qpubfi9t
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

**Comment by guoci** [comment] 2023-11-10 19:06
@jossmi you need to install git

**Comment by jossmi** [comment] 2023-11-10 19:15
Thanks, but forgive my naivete - I have installed Git, but does it need to be in the same directory as python? A bit more context on the command to run would be helpful.

**Comment by fcyu** [comment] 2023-11-10 19:37
Hi @jossmi ,

Make sure that your shell environment can find your git (i.e., your git in in the path). If you don't know how to do that, I am sorry that you have to find a local IT support. It is hard for us to troubleshot your computer issue remotely,

Best,

Fengchao

**Comment by jossmi** [comment] 2023-11-10 20:57
Got it. I updated the system path with the location for git, restarted my computer, and the commend worked fine. Re-ran my search and that worked as well. Thanks!
