### ISSUE TITLE
IonQuant update using FragPipe GUI fails to move to latest version

### ISSUE THREAD

**Issue by tobiasko** [Nesvilab/FragPipe#694] opened 2022-05-30 08:51 UTC
**Describe the bug**

I updatetd to FragPipe v18.0 and on Linux (Debian) and started the GUI using X-forwarding to update individual components using the Download/Update feature. Unfortunately, updating IonQuant to the latest version fails, although the download starts and finishes without an error message.

<img width="606" alt="Screenshot 2022-05-30 at 10 43 55" src="https://user-images.githubusercontent.com/12233339/170954182-d1202339-839c-494b-b606-376c25ca2873.png">

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment] 2022-05-30 16:21
I cannot reproduce the error. Is there an `IonQuant-1.8.0.jar` in the `fragpipe/tools` directory? If so, can you specify the IonQuant path manually in FragPipe?

Best,

Fengchao

**Comment by tobiasko** [comment] 2022-05-31 06:58
This is the listing of the .../tools directory:

```
tobiasko@fgcz-c-073:~/fragpipe/tools$ ls -l
total 433640
-rwxr-xr-x 1 tobiasko SG_Employees     1486 May 27 12:04 batmass-consumer.jar
-rw-r--r-- 1 tobiasko SG_Employees 29719750 Sep 30  2020 batmass-io-1.19.5.jar
-rwxr-xr-x 1 tobiasko SG_Employees 29734836 Mar 10  2021 batmass-io-1.22.1.jar
-rwxr-xr-x 1 tobiasko SG_Employees 30911044 Dec 22 12:13 batmass-io-1.23.6.jar
-rwxr-xr-x 1 tobiasko SG_Employees 33982406 May 27 12:04 batmass-io-1.25.5.jar
-rwxr-xr-x 1 tobiasko SG_Employees  2213560 May 27 12:04 commons-math3-3.6.1.jar
drwxr-xr-x 4 tobiasko SG_Employees       86 May 30 10:32 diann
drwxr-xr-x 2 tobiasko SG_Employees       82 May 30 10:32 diann_so
-rw-r--r-- 1 tobiasko SG_Employees 11386934 Sep 30  2020 dia_umpire_se-2.1.5.jar
-rwxr-xr-x 1 tobiasko SG_Employees 14279851 Mar 10  2021 DIA_Umpire_SE-2.2.1.jar
-rwxr-xr-x 1 tobiasko SG_Employees 14280562 Dec 22 12:13 DIA_Umpire_SE-2.2.3.jar
-rwxr-xr-x 1 tobiasko SG_Employees 29218097 May 27 12:04 DIA_Umpire_SE-2.2.8.jar
drwxr-xr-x 2 tobiasko SG_Employees       36 May 30 10:32 fasta
drwxr-xr-x 3 tobiasko SG_Employees       51 May 27 12:04 FP-PDV-1.0.1
-rwxr-xr-x 1 tobiasko SG_Employees  3919717 May 27 12:04 grppr-0.3.23.jar
drwxr-xr-x 2 tobiasko SG_Employees      149 May 27 12:04 hipparchus-1.8
-rw-r--r-- 1 tobiasko SG_Employees 43484008 Sep 30  2020 ionquant-1.4.4.jar
-rwxr-xr-x 1 tobiasko SG_Employees 43513559 Mar 10  2021 ionquant-1.5.5.jar
-rwxr-xr-x 1 tobiasko SG_Employees 22677074 Dec 22 12:13 ionquant-1.7.19.jar
-rw-r--r-- 1 tobiasko SG_Employees 22468020 May 30 10:43 IonQuant-1.8.0.jar
drwxr-xr-x 2 tobiasko SG_Employees     4096 Dec 22 12:13 javacpp-presets-platform-1.5.6-bin
-rwxr-xr-x 1 tobiasko SG_Employees  1604073 May 27 12:04 jfreechart-1.5.3.jar
-rwxr-xr-x 1 tobiasko SG_Employees  9509337 Dec 22 12:13 msbooster-1.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees 24312955 May 27 12:04 msbooster-1.1.4.jar
drwxr-xr-x 3 tobiasko SG_Employees       24 Mar 10  2021 MSFragger-3.2
drwxr-xr-x 3 tobiasko SG_Employees     4096 May 30 10:35 MSFragger-3.5
-rw-r--r-- 1 tobiasko SG_Employees 74105674 May 30 10:35 MSFragger-3.5.zip
-rwxr-xr-x 1 tobiasko SG_Employees    30794 May 27 12:04 msfragger_pep_split.py
-rw-r--r-- 1 tobiasko SG_Employees     6410 Sep 30  2020 msfragger_pep_split.pyz
-rwxr-xr-x 1 tobiasko SG_Employees    42286 Mar 10  2021 original-crystalc-1.3.2.jar
-rwxr-xr-x 1 tobiasko SG_Employees    43686 Dec 22 12:13 original-crystalc-1.4.2.jar
-rwxr-xr-x 1 tobiasko SG_Employees    43607 May 27 12:04 original-crystalc-1.4.4.jar
drwxr-xr-x 2 tobiasko SG_Employees     4096 May 30 10:32 percolator-305
drwxr-xr-x 2 tobiasko SG_Employees       96 Jan  5 16:09 philosopher
drwxr-xr-x 2 tobiasko SG_Employees       96 May 30 10:43 philosopher_v4.2.2_linux_amd64
-rw-r--r-- 1 tobiasko SG_Employees   169940 Sep 30  2020 ptmshepherd-0.4.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees   219879 Mar 10  2021 ptmshepherd-1.0.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees   352128 Dec 22 12:13 ptmshepherd-1.2.6.jar
-rwxr-xr-x 1 tobiasko SG_Employees   385364 May 27 12:04 ptmshepherd-2.0.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees   641551 May 27 12:04 smile-core-2.6.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees   508528 May 27 12:04 smile-math-2.6.0.jar
drwxr-xr-x 7 tobiasko SG_Employees     4096 May 30 10:32 speclib
-rw-r--r-- 1 tobiasko SG_Employees    30986 Sep 30  2020 tmt-integrator-2.1.4.jar
-rwxr-xr-x 1 tobiasko SG_Employees    33957 Mar 10  2021 tmt-integrator-2.4.0.jar
-rwxr-xr-x 1 tobiasko SG_Employees    36270 Dec 22 12:13 tmt-integrator-3.2.1.jar
-rwxr-xr-x 1 tobiasko SG_Employees    39743 May 27 12:04 tmt-integrator-3.3.3.jar
-rwxr-xr-x 1 tobiasko SG_Employees     2768 May 27 12:04 umpire-se_default.params
-rwxr-xr-x 1 tobiasko SG_Employees    48082 May 27 12:04 unimod_20191002_RNAadducts.txt
tobiasko@fgcz-c-073:~/fragpipe/tools$ 
```

**Comment by tobiasko** [comment] 2022-05-31 07:01
And yes, I can manually select `IonQuant-1.8.0.jar` and the GUI is fine. Could it be the capital `i` that creates this effect?

**Comment by tobiasko** [comment] 2022-06-02 11:38
But coming back to your suggestion: The problem is solved once only a single IonQuant version is found in `.../tools.`

**Comment by fcyu** [comment] 2022-06-11 02:49
Fixed in https://github.com/Nesvilab/FragPipe/commit/908a8a3e36e33051ced4e7b32d81b7c56590437e

Best,

Fengchao

**Closed by fcyu** 2022-06-11 02:49 UTC
Labels: FragPipe
