### ISSUE TITLE
Messed up files broke FragPipe

### ISSUE THREAD

**Issue by ProteomicsPSG** [Nesvilab/FragPipe#1401] opened 2024-01-08 15:35 UTC
- Describe the issue or question:
I recently updated the whole FragPipe workflow ( all tools updated for V21.0, 8jan 2024). 
Standaard DDA search runs repeatedly into error message after PeptideProphet. I tried several datasets.. same error.
No idea  how to solve this..

System OS: Windows 10, Architecture: AMD64
Java Info: 11.0.9.1, OpenJDK 64-Bit Server VM, AdoptOpenJDK
.NET Core Info: N/A
Version info:
FragPipe version 21.0
MSFragger version 4.0
IonQuant version 1.10.12
Philosopher version 5.1.0

...
INFO[16:14:28] Done                                         
Process 'PeptideProphet' finished, exit code: 0
Rewrite pepxml [Work dir: D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5]
.....   ......
Fixing pepxml: D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5\interact.pep.xml
Didn't find correct mapping for raw file path in pepxml: D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5/G4Gr_SDS_D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5/G4Gr_SDS_A101_5xWriting output to: D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5\interact.pep.xml1389634936862962355.temp-rewriteA101_5xWriting output to: D:\Fragger_output\G4Gr_SDS_Mix-101_tst\A101_5\interact.pep.xml1389634936862962355.temp-rewrite
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

NB  please note inconsistency in forward and backward slashes in folder path of output .xml path  as generated by the script !!

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-01-08_16-14-31.txt](https://github.com/Nesvilab/FragPipe/files/13862989/log_2024-01-08_16-14-31.txt)

**Comment by fcyu** [comment] 2024-01-08 15:42
Can you uncheck `single combined pepxml file per experiment/group` and try again?

![image](https://github.com/Nesvilab/FragPipe/assets/6926299/c791301e-0395-4f88-8b82-a94f865250b5)

Best,

Fengchao

**Comment by fcyu** [comment] 2024-01-08 15:52
You need to rerun from scratch,

**Comment by ProteomicsPSG** [comment] 2024-01-08 16:14
started a new search from scratch, with "deselected" single combined pepXML file....
Same error message

Again  NB the inconsistent forward and backslashes in the last output path in the log file. Could taht  hint to an error??
.....
Fixing pepxml: D:\Fragger_output\G4Gr_SDS_Mix-101_2ndtst\A101_1\interact-G4Gr_SDS_A101_01.pep.xml
Didn't find correct mapping for raw file path in pepxml: D:\Fragger_output\G4Gr_SDS_Mix-101_2ndtst\A101_1/G4Gr_SDS_A101_01Writing output to: D:\Fragger_output\G4Gr_SDS_Mix-101_2ndtst\A101_1\interact-G4Gr_SDS_A101_01.pep.xml349473914224268326.temp-rewrite
Process 'Rewrite pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping
......
[log_2024-01-08_17-10-17.txt](https://github.com/Nesvilab/FragPipe/files/13863512/log_2024-01-08_17-10-17.txt)

**Comment by fcyu** [comment] 2024-01-08 16:21
Then, I am clueless now unless taking a look at your files. If you like, please upload all files to https://www.dropbox.com/request/jtkhkVvxGfsh5lBLsRad

> Again NB the inconsistent forward and backslashes in the last output path in the log file. Could taht hint to an error??
 
Although I don't know what "NB" means, I don't think this is the cause of the error.

Best,

Fengchao

**Comment by ProteomicsPSG** [comment] 2024-01-08 16:42
I have now re-run the search with only 2 files. Then zipped the complete FragPipe output folder  plus the zippped .raw files together  and uploaded them to the given Dropbox.

Also these 2 files give the same error message:
...
 Didn't find correct mapping for raw file path in pepxml: ......

Thanks for your help.

**Comment by fcyu** [comment] 2024-01-08 17:47
Thanks for your files. Something does not seem right in your `*.pep.xml` files:

```xml
<msms_run_summary base_name="D:\Fragger_output\G4Gr_SDS_Mix2fileTst\Amix5_6/G4Gr_SDS_Amix5_6" raw_data_type="raw" raw_data="raw">
```

The above like should be 

```xml
<msms_run_summary base_name="F:\github_issues\github_fragpipe_1401\G4Gr_SDS_Amix5_6_uncalibrated" raw_data_type="mzML" raw_data="mzML">
```

I don't know why it happened. Maybe some files were messed up (one indication is that your log has the messages printed by logback, which there should not be). I suggest you delete all FragPipe, MSFragger, Philosopher, and IonQuant folders. Download new ones to **new** folders. And then use the new downloaded FragPipe. If the error persists, please convert your raw files to mzML format according to the tutorial: https://fragpipe.nesvilab.org/docs/tutorial_convert.html

Best,

Fengchao

**Comment by ProteomicsPSG** [comment] 2024-01-09 12:51
Hi Fengchao, 
Thank you for  your efforts and suggestion. 
I completely new installation of FragPipe + modules  in itself was not enough. 
But after delecting the (un)calibrated mzML files and runnign with Peptide/ProteinProhet validation, the search was succesfull.   I have now also tried some other files which were succesful. 

\Halas, \  With MS booster and percolator (not PEPTIDEPROPHET) I still run into an error.:  
last lines:  Found 23307 test set PSMs with q<0.01.
Selected best-scoring PSM per file+scan+expMass (target-decoy competition): 32968 target PSMs and 9311 decoy PSMs.
Calculating q values.
Final list yields 23313 target PSMs with q<0.01.
Calculating posterior error probabilities (PEPs).
Processing took 7.9960 cpu seconds or 8 seconds wall clock time.
Process 'Percolator' finished, exit code: 0
Percolator: Convert to pepxml [Work dir: D:\Fragger_output\G4Gr_SDS_Mix_Nw2fileTst_BoosterPercolator\Amix5_5]
C:\MyPrograms\FragPipe21p1\jre\bin\java.exe -cp C:\MyPrograms\FragPipe21p1\lib/* com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML G4Gr_SDS_Amix5_5.pin G4Gr_SDS_Amix5_5 G4Gr_SDS_Amix5_5_percolator_target_psms.tsv G4Gr_SDS_Amix5_5_percolator_decoy_psms.tsv interact-G4Gr_SDS_Amix5_5 DDA 0.5 D:\Data_Proteomics\Data_G4Gr_SDS_dec23\G4Gr_SDS_Amix5_5_calibrated.mzML
Exception in thread "main" java.lang.NumberFormatException: For input string: "0,6299"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source)
	at java.base/java.lang.Float.parseFloat(Unknown Source)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.percolatorToPepXML(PercolatorOutputToPepXML.java:340)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.main(PercolatorOutputToPepXML.java:59)
Process 'Percolator: Convert to pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 16 remaining tasks

**Comment by fcyu** [comment] 2024-01-09 12:59
This is a known issue: https://github.com/Nesvilab/FragPipe/issues/1378

Please follow the instruction in https://github.com/Nesvilab/FragPipe/issues/1378#issuecomment-1864566848 to resolve it.

Best,

Fengchao

**Comment by ProteomicsPSG** [comment] 2024-01-10 15:21
Hi Fengchao,
Thank you for your help.
Changing the location and number notation (again) helped indeed to get MS Booster and Percolator working again.

Thank you, a lot, for developing such a great software environment as FragPipe and its tools.
😉

Cheers,
Twan

**Comment by fcyu** [comment] 2024-01-10 16:48
Hi Twan,

You are welcome. 

I will close this ticket but feel free to contact us if you have any questions in the future.

Best,

Fengchao

**Closed** 2024-01-10 16:49 UTC
