### ISSUE TITLE
IonQuant terminated due to "bufferSize must be >0" error

### ISSUE THREAD

**Issue by wyu** [Nesvilab/FragPipe#686] opened 2022-05-21 21:26 UTC
Thanks for providing such a wonderful suite of tools for the community. We're trying to search a very large LFQ dataset (PXD008840) in FragPipe on a Windows workstation with 256GB of RAM. After a few days of intense search, it crashed at the IonQuan step as shown below. The log file is attached. 

Is it possible this is related to the size of the dataset? A quick look-up for this message suggested that the data to be serilized might have exceeded the limit of 'int' type.
https://github.com/protocolbuffers/protobuf/issues/8075

Thanks!
Wen

java.lang.IllegalArgumentException: bufferSize must be >= 0
	at com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.<init>(CodedOutputStream.java:2242)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.<init>(CodedOutputStream.java:2712)
	at com.google.protobuf.CodedOutputStream.newInstance(CodedOutputStream.java:105)
	at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:82)
	at k.a(Unknown Source)
	at k.<init>(Unknown Source)
	at s.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-05-21 15:12:43 [ERROR] - bufferSize must be >= 0
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1 remaining tasks

----------------------
## If you're submitting a bug report, please attach log file

The log file can be saved from FragPipe:
[error_log_2022-05-21_17-14-00.txt](https://github.com/Nesvilab/FragPipe/files/8748357/error_log_2022-05-21_17-14-00.txt)

- by clicking the `Export Log` button on the `Run` tab.
- or just copy text from the output console on `Run` tab to a text file.

**Comment by fcyu** [comment] 2022-05-21 21:28
Can you share the log file with us?

Thanks,

Fengchao

**Comment by wyu** [comment] 2022-05-22 20:14
Sorry, I thought I had included in the original post. Here it

Wen

[error_log_2022-05-21_17-14-00.txt](https://github.com/Nesvilab/FragPipe/files/8750197/error_log_2022-05-21_17-14-00.txt)
 is.

**Comment by fcyu** [comment] 2022-05-22 21:09
> A quick look-up for this message suggested that the data to be serilized might have exceeded the limit of 'int' type.

I don't think it is the cause because after "2022-05-21 15:10:50 [INFO] - Updating Philosopher's tables...", IonQuant started to deserialize the data, not serialize it. Since it has successfully serialized the data in the above stages, there might be something unexpected happed. Can you run IonQuant again to see if you can reproduce it?

Thanks,

Fengchao

**Comment by wyu** [comment] 2022-05-23 00:03
I'm running the IonQuan step again without MBR or MaxLFQ. Do you think the RAM exhaustion is an issue? It's pushing against the limit of 256GB as we're running another instance of FragPipe for a smaller TMT dataset at the same time. 

Wen

**Comment by fcyu** [comment] 2022-05-23 00:19
Also, I see you put hundreds of runs in one experiment. I don't think it is a good idea because IonQuant will collapse redundant peptides from the same experiment and report one intensity for one peptide. Same for ions, modified peptides, and proteins. Normally, only (fractionated) runs from the same biological experiment and replicate are assigned to the same experiment in IonQuant.

You might need to read the tutorial first: https://fragpipe.nesvilab.org/docs/tutorial_fragpipe.html#multi-experiment-report

Best,

Fengchao

**Comment by wyu** [comment] 2022-05-23 00:41
Good point! I'll change the sample manifest so each sample would be its own experiment. Do I need to re-run the ID steps (Msfragger & Validation) after the change?

**Comment by fcyu** [comment] 2022-05-23 00:44
Yes, you have re-run from everything if you don't know how to re-organize pepXML, interact.pep.xml, and pin files. If you do, you just need to re-run from the FDR filtering and reporting.

Best,

Fengchao

**Closed** 2022-05-23 19:37 UTC

**Comment by wyu** [comment] 2022-05-24 00:51
A new error occurred when I re-run the IonQuan step without MBR and MaxLFQ. Giving up for now and resubmit the search with the correct Experiment config.

Thanks!
WEn
 
[error_log_2022-05-23_20-43-09.txt](https://github.com/Nesvilab/FragPipe/files/8758743/error_log_2022-05-23_20-43-09.txt)

2022-05-21 15:10:50 [INFO] - Quantifying...
2022-05-21 15:10:50 [INFO] - Updating Philosopher's tables...
java.lang.IllegalArgumentException: bufferSize must be >= 0
	at com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder.<init>(CodedOutputStream.java:2242)
	at com.google.protobuf.CodedOutputStream$OutputStreamEncoder.<init>(CodedOutputStream.java:2712)
	at com.google.protobuf.CodedOutputStream.newInstance(CodedOutputStream.java:105)
	at com.google.protobuf.AbstractMessageLite.writeTo(AbstractMessageLite.java:82)
	at k.a(Unknown Source)
	at k.<init>(Unknown Source)
	at s.<init>(Unknown Source)
	at ionquant.IonQuant.main(Unknown Source)
2022-05-21 15:12:43 [ERROR] - bufferSize must be >= 0
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
