### ISSUE TITLE
Incorrect input files broke the workflow when running from the middle steps

### ISSUE THREAD

**Issue by mremachine1** [Nesvilab/FragPipe#1384] opened 2023-12-21 19:39 UTC
here is the error:
ERROR in ch.qos.logback.classic.joran.JoranConfigurator@2d554825 - Could not find valid configuration instructions. Exiting.
Process 'Rewrite pepxml' finished, exit code: 1
here is the run command:
/fragpipe --headless --threads '60' --ram '440' --config-philosopher 'pathto/philosopher' --workflow /pathtoworkflow/exposomics_fragpipe_post_msfragger.workflow --manifest /pathtomanifest/exposomics_post_fragger.fp-manifest --workdir /workingdirpath

and ive attached the log manifest and workflow as a zip folder
[exposomics_fragpipe_post_msfragger.zip](https://github.com/Nesvilab/FragPipe/files/13745627/exposomics_fragpipe_post_msfragger.zip)

should I delete the interact.pepxml and try to rerun?

The mzMLs are actually calibrated but were renamed to get around a previous run issue

**Comment by fcyu** [comment] 2023-12-21 19:57
I think the file names and the file contents are messed up because the error message is 
```shell
Not all given paths exist: Optional[/fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E51_Q2_calibrated.mzML]
```

And there is no `JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E51_Q2_calibrated.mzML` in your input files:
```shell

LCMS files:
  Experiment/Group: 
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E48_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E49_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E49_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E50_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E50_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E51_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E51_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E52_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E52_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E53_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E53_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E54_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_E54_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_1_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_1_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_2_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_2_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_2_reinj_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC1_2_reinj_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC2_1_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC2_1_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC2_2_reinj_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B5_EQC2_2_reinj_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E55_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E55_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E56_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E56_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E57_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E57_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E58_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E58_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E59_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E59_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E60_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E60_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E61_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E61_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E62_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E62_Q2.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E63_Q1.mzML	DDA
  - /fastscratch/myscratch/smburke/Exposomics_post_fragger_copy/JS-E480-CS_230630_GroopmanJ_SmithJ_FennaExposome_B6_E63_Q2.mzML	DDA
```

This kind of discrepancy is mainly because you run the workflow from the middle but didn't get the input files and intermediate files in the right place. I think the most straightforward way for you is re-run everything from scratch.

Best,

Fengchao

**Comment by mremachine1** [comment] 2023-12-21 20:01
Hi Feng chao,
I would do that but this error occurs when I try that suggestion. This issue was marked as closed but was not resolved
https://github.com/Nesvilab/philosopher/issues/475#issue-2017842105

**Comment by fcyu** [comment] 2023-12-21 20:09
Then, I will close this issue and reopen that one. But I don't think it is easy for us to figure out the cause of the error unless you share all of your files with us.

Best,

Fengchao

**Closed by fcyu** 2023-12-21 20:09 UTC
