### ISSUE TITLE
Lists of proteins from IonQuant and MSstats does not match?

### ISSUE THREAD

**Issue by MNTsnowman** [Nesvilab/FragPipe#511] opened 2021-11-06 08:44 UTC
Hi Fragpipe team

I have recently analyzed some data with FragpipeV16, here i noted that the list or proteins generated by IonQuant is not the same list as generated by MSstats when i use the MSstats.csv file generated by Fragpipe. To me this seems odd, I mean, I would expect the lists to be similar when they orriginate from the same analysis?

In my case, i got a list of 3755 Identified proteins by IonQuant (2219 of these have atleast 2 uniqie PSMs) while the list in MSstats only contains 1051 unique protein ID. 

So, I guess the quiestion is simple; why this difference? Are there any settings that I missed? Can i somhow get a propper list to MSstats with all proteins from IonQuant? If yes, can i get this list without rerunning the entire analysis?

And a bonus question, lately I discovered that there is an R package called MSstatsPTM (http://www.bioconductor.org/packages/release/bioc/html/MSstatsPTM.html), and it seems to need some different kind of input data than the MSstats.csv fil generated by FragPipe (they are not replying with the difference). Is there any chance that you can add compatibility with this package somewhere down the line?

I hope you can help, and thank you for your awsome work.

Martin

**Comment by fcyu** [comment] 2021-11-06 14:32
Hi Martin,

Can you tell us what file you are using to get the list of proteins from IonQuant?

As to the MSstatsPTM, we will discuss internally and keep you posted.

Best,

Fengchao

**Comment by MNTsnowman** [comment] 2021-11-08 08:44
Hi Fengchao

Thanks a lot for the quick reply, and sorry for the delay.

I have tried to use both the combined_peptide.tsv and the combined_prptein.tsv files. Maybe I should look somewhere else?

However, as the MSstats file contains peptides, my best guess would be the combined_peptide.tsv file. I then sort the list of prtorein IDs from the combined_peptided.tsv file so that peptides with all "0" in the "intensity" colums are left out (hint, only "observed" peptides are thus included). I then remove dublicate protein IDs, the length of this list is not the same as the lenght of unique protein IDs from the MSstats file. Maybe I'm doing it wrong, i'm just trying to get the numbers to match up.

And thank you for considering the MSstatsPTMs. I wish i could tell you more about how to use it, but i have not made it work yet, nor have i spend much time at trying. but it complains about the input format when using the MSstats.csv file generated by fragpipe, somethin about a missing PTM column?

Kind regards
Martin

**Comment by fcyu** [comment] 2021-11-08 14:57
Hi Martin,

No worries!

I think I might know the reason if you were using FragPipe 16. In that version, the `combined_peptide.tsv` file is generated by Philosopher with 1% peptide FDR. While the `MSstats.csv` is generated by IonQuant with 1% PSM and protein FDR. 

I just did a testing with FragPipe 17 and the numbers match. 

As to the MSstatsPTMs, I never used that before. We will discuss how to generate the file for it. We might also generate files for MSstatsTMT.

Best,

Fengchao

**Comment by MNTsnowman** [comment] 2021-11-09 14:15
Hi Fengchao

Sorry for the delay, i just tried to reanalyze the dataset via FragpipeV17. And the issue remains.

So maybe i should go about this differently, therefore i was wondering, how do you get identical lists of proteins from the MSstats.csv file and the combined_peptide.tsv file from FragpipeV17?

Also, i noted that the MSstats.csv file contains PTM annotations in the form of [xx.xxx] while the combined_peptide.tsv file has no PTM information at all. Maybe this could be part of the explanation?

Kind Regards
Martin

**Comment by MNTsnowman** [comment] 2021-11-09 17:16
Hi Fengchao

I could send you the different combined_xx.tsv files as well as the MSstats.csv file. I guess the rest is way to big to send.. But please send a link and I'll look at it tomorrow. :)

Also, and this is a bit off topic, i noted that the output from v17 now has a STY_79.9663.tsv fil generated by PTMProphet, just out of curiosity would it be possible to make this lsit of PTMs sync with the applied list of PTMs from the MSFragger tab? I always forget to update it... 

Kind Regards
Martin

**Comment by MNTsnowman** [comment] 2021-11-09 19:29
Hi Fengshao

I had a little time, so I uploaded the files. Have fun.

Best,
Martin

**Comment by fcyu** [comment] 2021-11-09 20:59
Hi Martin,

Thanks for your files. I think I might find the reason.

1. There are 24 runs, but 12 experiments. I guess there are two replicates in each experiment although I don't have the log file to support my guess.
2. An ion/transaction in the MSstats.csv file must have non-zero intensities in at least two run. I added this filter because MSstats will print a warning and discard the ion when the ion is only quantified in one run. Since those "single-run" ions will be discarded in anyway, I remove them from the MSstats.csv to avoid the warning message from MSstats.

To verify my guess, can you run the data with 24 experiments, and check if the number of proteins matches?

Best,

Fengchao

**Comment by MNTsnowman** [comment] 2021-11-10 11:47
Hi Fengchao

Sorry about the delay, rerunning the data analysis takes atleast 9 houers. So, please no more of that?

Just to clarify the setup, you are right about the 24 runs representing 12 experiments. Here i have maintained the two groups as from before. I hope that's fine.

I uploaded the new files, from the new run where 24 unique biorep ides were provided while maintaining the groups. When i browse through the combined_xxx-tsv files i can recreate the same lists in all cases, however, the MSstats file only contains a little less than 1/3 of these IDs.

So where are the rest? Maybe the FDR filtering on the protein level plays a rolle? If so, how do i get a complete list of all observed poteins (with sufficient FDR, 0.01) observed throughout all samples (once in one sample with propper FDR), not just those that can be found in all samples (once in all samples with propper FDR)? I hope you see understand, otherwise let me know. :)

Best´
Martin

**Comment by fcyu** [comment] 2021-11-10 14:38
Hi Martin,

The numbers match. 

As I said "An ion/transaction in the MSstats.csv file must have non-zero intensities in **at least two** runs. ". If you count the number of nonredundant ions quantified in at least two runs, there are 1052 proteins, which is the same as those from MSstats.csv.

I put the table in the attachment so that you can reproduce my counting.

> So where are the rest? Maybe the FDR filtering on the protein level plays a rolle? If so, how do i get a complete list of all observed poteins (with sufficient FDR, 0.01) observed throughout all samples (once in one sample with propper FDR), not just those that can be found in all samples (once in all samples with propper FDR)? I hope you see understand, otherwise let me know. :)

Since the numbers match, I think these are no longer valid questions. Am I correct?

Best,

Fengchao

[martin thesbjerg - combined_ion.zip](https://github.com/Nesvilab/FragPipe/files/7513488/martin.thesbjerg.-.combined_ion.zip)

**Comment by MNTsnowman** [comment] 2021-11-10 15:22
Hi Fengchao

Observed in 2 runs, that was the key. I get it now, it makes sence, i can recreate the lists. Thank you so much for your time and patience.

Please, could you remove the zip file?

Short answer for others that may read in the furure: use the combined_ion.tsv file. filter (in excel) on the [sampleID]Intensity colums, here pick out the rows with atleast two values larger than 0. Now you have the peptides that are used for MSstats.csv. In here you can filter for unique both peptides and proteins. Thats it. :)

**Comment by fcyu** [comment] 2021-11-10 15:31
Sure. To remove the zip file entirely, I have to delete my whole reply (editing the reply would leave a history version). Thus, I paste my original reply in the following.

Best,

Fengchao

> Hi Martin,
> 
> The numbers match.
> 
> As I said "An ion/transaction in the MSstats.csv file must have non-zero intensities in at least two runs. ". If you count the number of nonredundant ions quantified in at least two runs, there are 1052 proteins, which is the same as those from MSstats.csv.
> 
> I put the table in the attachment so that you can reproduce my counting.
> 
> So where are the rest? Maybe the FDR filtering on the protein level plays a rolle? If so, how do i get a complete list of all observed poteins (with sufficient FDR, 0.01) observed throughout all samples (once in one sample with propper FDR), not just those that can be found in all samples (once in all samples with propper FDR)? I hope you see understand, otherwise let me know. :)
> 
> Since the numbers match, I think these are no longer valid questions. Am I correct?
> 
> Best,
> 
> Fengchao

**Comment by fcyu** [comment] 2021-11-10 15:34
>  here pick out the rows with atleast two values larger than 0

I have to clarify that it should be at least two **runs** (not experiments) with values larger than 0. If there are experiments containing more than one run, you have to rerun the analysis to make each experiment only contain one run.

I added this filter because MSstats will print a warning and discard the ion when the ion is only quantified in one run. Since those "single-run" ions will be discarded in anyway, I remove them from the MSstats.csv to avoid the warning message from MSstats.

I will close this issue since it is resolved.

Best,

Fengchao

**Closed by fcyu** 2021-11-10 15:34 UTC
Labels: FragPipe, IonQuant
