### ISSUE TITLE
Error while creating SpectrumMatch in database (FP-PDV)

### ISSUE THREAD

**Issue by AdamKarpinski** [Nesvilab/FragPipe#709] opened 2022-06-08 12:17 UTC
Hi, 

I was extremely happy to see the application of PDV and its usage within the FragPipe workflow. 

I am currently running 12 fractions of TMT10plex, everything works fine, but I am unable to create a database for FP-PDV to visualize the PSMs. 

I get two errors - 

1st. "An error occured while creating SpectrumMatch in database." 

2nd. "Failed to parse results."

I am attaching the screenshots. 

All the best, 

Adam
![FP-PDV_2](https://user-images.githubusercontent.com/67690458/172613942-0fa25e7e-81da-4a5a-a6b2-a7f9005c61db.png)
![FP-PDV](https://user-images.githubusercontent.com/67690458/172613945-4690710b-8e6a-4fb8-a8b5-b8308c8dff41.png)

**Comment by anesvi** [comment] 2022-06-08 13:21
Maybe. We need to investigate. I cc Kai Li who is leading FragPipe-PDV viewer work. We will test on some bigger datasets ourselves first. We did before, but need to check with the release version

You can search separately for now, but of course for real analysis you (for TMT-Integrator etc) you need all fractions in one folder

Alexey

**Comment by AdamKarpinski** [comment] 2022-06-08 14:11
Just to follow-up, I've searched all 12 mzML files within one search but as different experiments, and I had no issue with visualizing the data for all the experiments. 

It seems that the issue is the size of the dataset when all fractions are searched as one experiment for TMT-Integrator. 

Best regards, 

Adam

**Comment by KaiLiCn** [comment] 2022-06-08 14:59
Hi Adam,

Sorry about it. Could you please share your `*.fp-manifest` file with me? It's ok to give me a screenshot. This file is inside your result folder.

Kai

**Comment by AdamKarpinski** [comment] 2022-06-08 18:12
Hi, 

the left hand side is the .fp-manifest file from the search with 12 mzML files search as separate experiments, the right hand side is the .fp-manifest file from the 12 mzML files searched as one experiment for TMT-Integrator.

All the best, 

Adam

![FP-PDV_3](https://user-images.githubusercontent.com/67690458/172687221-733ff291-b184-4c09-a029-9155db103c7d.PNG)

**Comment by KaiLiCn** [comment] 2022-06-08 18:27
Appreciate it. I am reproducing this issue on my side and fix it soon.

**Comment by KaiLiCn** [comment] 2022-06-08 19:27
Could you please share the `psm.tsv` and `*annotation.txt` table with us? They're in the result folder. `*annotation.txt` is the annotation file for each sample for TMT-Integrator.

**Comment by AdamKarpinski** [comment] 2022-06-08 21:11
Hey, sure, I'm attaching the annotation file, I am unable to upload the psm.tsv as it is too big (25 MB limit, the file is 46 MB). 

I can send it from my e-mail to you, is the e-mail address from GitHub ok? (likaicnsh@gmail.com) 

Best regards, 

Adam

[Fractions_annotation.txt](https://github.com/Nesvilab/FragPipe/files/8865014/Fractions_annotation.txt)

**Comment by KaiLiCn** [comment] 2022-06-08 23:30
Sorry for the late reply. Yes, the email address is correct.

Best,
Kai

**Comment by KaiLiCn** [comment] 2022-06-09 16:10
Hi Adam,

I have found the bug and fixed it. The reason is some column names in `psm.tsv` start with digit number. And this causes database bugs. We will update it soon later.

Best
Kai

**Comment by AdamKarpinski** [comment] 2022-06-10 07:46
Hi Kai, 

OK, thank you very much, I will keep that in mind with next analysis. 

Thank you.

All the best, 

Adam

**Comment by fcyu** [comment] 2022-06-17 17:48
Fixed in https://github.com/Nesvilab/FragPipe/commit/d7a0dbcc2cdbc19773ed466e1fe5c83b2ed809a5

**Closed by fcyu** 2022-06-17 17:48 UTC
Labels: FP-PDV
