### ISSUE TITLE
IonQuant: out of bounds error

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe#309] opened 2021-02-18 19:04 UTC
Dear Fragpipe Team

I am running FragPipe via Xwindow-GUI on a Linux machine. I get an IonQuant error for "index out of bounds".
Do you have any idea what went wrong?

There are 15 raw files in the game and a huge metaproteomicsDB of 8.2G (which I manage to run successfully to run the full FragPipe-MBR workflow for 3 test files).

Best regards
jonas

///
2021-02-18 09:27:27 [INFO] - matched run percentage: 0.1495889380762246
2021-02-18 09:27:27 [INFO] - Fitting a mixture model...
2021-02-18 09:27:27 [INFO] - Estimating match-between-runs FDR...
2021-02-18 09:27:30 [ERROR] - Index 11095 out of bounds for length 10001
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment] 2021-02-18 20:16
It is the duplicate of https://github.com/Nesvilab/FragPipe/issues/308

**Closed by fcyu** 2021-02-18 20:16 UTC
