### ISSUE TITLE
False alarm

### ISSUE THREAD

**Issue by p-bell** [Nesvilab/FragPipe#1362] opened 2023-12-12 06:43 UTC
I'm analysing a TMT-16plex (MS3 quant) dataset acquired on a Thermo Ascend.

FragPipe identifies plenty (~4000) of TMTpro-labelled PSMs, but almost none of them are quantified (<20). The same dataset analysed in Proteome Discoverer yields thousands of quantified PSMs.

I'd prefer to use FragPipe for analysis - please can you advise if there is anything in the logs suggesting an issue?

Note - I'm using most recent MSConvert version to generate a .mzml file from the .raw. 

Thanks a lot,
Pete

[log_2023-12-11_22-06-42.txt.zip](https://github.com/Nesvilab/FragPipe/files/13644581/log_2023-12-11_22-06-42.txt.zip)

**Comment by anesvi** [comment] 2023-12-12 12:45
You only sent a partial log, and from that I cannot spot any issue. Did you load our default workflow? We would need to see your data (mzML file and the database). We can also give you a pre-release of FragPipe 21 where we fixed some issues, if you are willing to test using that version.

**Comment by p-bell** [comment] 2023-12-12 18:07
Thanks for looking into the issue. Yes I've tried the TMT16-MS3 workflow (I think the log that I uploaded was from a modified version of that workflow though).

Thanks that would be great to test FragPipe 21. I can also pass on the mzML / database - is there an email address I can send a download link to?

Thanks again

**Comment by fcyu** [comment] 2023-12-12 18:11
Here is the link to upload your files: https://www.dropbox.com/request/sCamkzbVhuSIT1rdJxRi
Here is the link to download the pre-released versions: https://www.dropbox.com/t/f9j1j0ynCMr30ZTc

Best,

Fengchao

**Comment by p-bell** [comment] 2023-12-12 18:49
Thanks, I've uploaded 2x .mzmls with their corresponding databases, plus a README with further info relevant for parameters.

I'll also attempt analysis with the pre-release version. Please let me know if there's any other info I can provide that will help.

Thanks! 
Pete

**Comment by fcyu** [comment] 2023-12-12 19:56
Hi Pete,

Thanks for your files. I have reproduced what you observed. After looking into the mzML file (PB05_2hr_SPSMS3RTS.mzML), those with 0 channel intensities have no MS3 scans. Could you double check that the data acquisition and conversion had no issue? 

Thanks,

Fengchao

**Comment by p-bell** [comment] 2023-12-12 21:50
Thanks Fengchao,

The same files in .raw format yielded quantitative data in Proteome Discoverer, so I suspect that its an issue with conversion to .mzml.

I followed the conversion instructions and used the most recent version of msconvert... I'm not sure what else to try. 

I've asked the team at Thermo if there's been any changes in how data from the Ascend are stored in .raw format vs previous instruments.

Would it help if I were to upload the .raw file?

Thanks again,
Pete

**Comment by fcyu** [comment] 2023-12-12 21:54
Hi Pete,

Yes, uploading your raw files will be very helpful.

Thanks,

Fengchao

**Comment by anesvi** [comment] 2023-12-12 21:54
Fengchao, maybe he can test pre-release if FragPipe with IonQuant

**Comment by fcyu** [comment] 2023-12-12 21:55
@anesvi I have tested using his file. Similar result. That was why I looked into the mzML file and found that most MS2 scans don't have MS3 scans.

Best,

Fengchao

**Comment by p-bell** [comment] 2023-12-12 22:36
Thanks - I've uploaded .raw files

**Comment by p-bell** [comment] 2023-12-13 00:12
Hi Fengchao,

Sorry for the confusion... I've just been notified that it was not the same file that had yielded quantitative data in Proteome Discoverer, there had been a mistake and I was given a different file which had used the new real-time search method. 

I suspect that there was no MS3 data in this file for the majority of peptides, because they were not selected for MS3 in real-time.

I tested the correct file and it gave >2000 quantified PSMs, which is far more in line with what we expected.

Apologies for the confusion and thanks again for your support.
Pete

**Comment by fcyu** [comment] 2023-12-13 00:15
Hi Pete,

Thanks for the timely update. I was just looking at your raw files and getting confused because the file and the converted mzML file have no issue. Your information explains everything. Then, I think it is good to close this issue now.

Best,

Fengchao

**Closed** 2023-12-13 00:31 UTC
