### ISSUE TITLE
Attempt to convert files back to mzXML fail by calling philosopher

### ISSUE THREAD

**Issue by jspaezp** [Nesvilab/FragPipe#139] opened 2019-09-19 19:09 UTC
* **I'm submitting a:**
  - [ ] problem running the software
  - [x] bug report
  - [ ] feature request
  - [ ] question

When attempting to run a workflow consisteing of DIA-Umpire > msfragger, the run fails due to `philosopher` being called in the wrong context.

All steps entailing the generation of `.mgf` files from the `.mzXML` succed but when fragpipe attempts to convert the file to `mzXML` again (to be searched by msfragger) because it is (I believe) calling `philosopher` instead of `msconvert`.

Output of a dry run:

```

...
/home/jspaezp/opt/philosopher_v1.5.1_linux_amd64/philosopher --format mzXML --intencoding 32 --mzencoding 32 --zlib /home/jspaezp/Documents/tmp/res/Sample_Q1.mgf
UmpireSe [Work dir: /home/jspaezp/Documents/tmp/res]
/home/jspaezp/opt/philosopher_v1.5.1_linux_amd64/philosopher --format mzXML --intencoding 32 --mzencoding 32 --zlib /home/jspaezp/Documents/tmp/res/Sample_Q2.mgf
UmpireSe [Work dir: /home/jspaezp/Documents/tmp/res]
/home/jspaezp/opt/philosopher_v1.5.1_linux_amd64/philosopher --format mzXML --intencoding 32 --mzencoding 32 --zlib /home/jspaezp/Documents/tmp/res/Sample_Q3.mgf
...

```

when running those commands on the terminal it (unsurprisingly) returns

```
Error: unknown flag: --format
Usage:
  philosopher [command]

Available Commands:
  abacus         Combined analysis of LC-MS/MS results
  cluster        Protein report based on protein clusters

...

```

Kindest wishes and amazing work,
Sebastian

**Comment by anesvi** [comment] 2019-09-19 19:45
It is trying to use msconvert embedded in philosopher, but apparently there is something wrong. We need to take a look.

Dmitry – I thought earlier we used msconvert directly (with path specified in DIA-Umpire TAB)?

**Comment by chhh** [comment] 2019-09-19 21:34
@jspaezp Thanks for the bug report, will fix promptly. Caused by differences in how the commands were formed and invoked on linux/win.
@anesvi That's only on Windows. On Linux it used msconvert built into philosopher.

**Comment by jspaezp** [comment] 2019-09-19 22:07
I was not aware that philosopher included msconvert, under what command can one call it (does not show up as an available command when calling `philosopher --help`)?

Thank you very much for your attention
Kindest wishes,
Sebastian

**Comment by anesvi** [comment] 2019-09-19 22:23
It got disabled in philosopher about six month ago (but FragPipe for Linux was not updated to reflect that). I think Dmitry will need to make a change in FragPipe to call stand-alone msconvert instead

**Comment by prvst** [comment] 2019-09-20 01:03
We decided to remove msconvert from philosopher because of a bug that was removing every file from the workspace. Since it was a serious problem, msconvert was completely removed. I might reconsider adding it back again in the near future after being sure that the bug was fixed.

For now I advise you to use the native msconvert from pwiz.

**Comment by chhh** [comment] 2019-09-20 01:15
@prvst Why did you close the ticket? We're in the middle of resolving the issue.

**Comment by prvst** [comment] 2019-09-20 18:12
sorry, wrong button

**Comment by chhh** [comment] 2019-09-20 20:31
@jspaezp Please try this new 11.0 pre-release: https://github.com/Nesvilab/FragPipe/releases/tag/11.0

**Comment by jspaezp** [comment] 2019-09-22 06:51
Hello @chhh I can confirm the new release works in windows and Linux.

Nonetheless, in linux it requires calling fragpipe as `export LC_ALL=C ; ./FragPipe ` due to a know bug in msconvert that makes it crash when locales are not set to `C` with the following error.

```
...
msconvert: loadlocale.c:129: _nl_intern_locale_data: Assertion `cnt < (sizeof (>
...

```

Thank you very much for for the help and quick bug fix.
Best,
Sebastian

**Comment by chhh** [comment] 2019-09-22 08:48
@jspaezp So the problem is that `LC_ALL=C` environment variable needs to be set? I didn't know about that bug in msconvert, but I can definitely add that env var to when starting the msconvert process, thanks for the info!

**Closed by chhh** 2019-09-22 08:48 UTC

**Comment by jspaezp** [comment] 2019-09-24 21:56
sounds perfect thank you very much @chhh and @anesvi , keep up the amazing work
