### ISSUE TITLE
MSFragger exit code 1

### ISSUE THREAD

**Issue by Peilou** [Nesvilab/FragPipe#339] opened 2021-03-26 19:12 UTC
Dear Fragpipe team,

I am analyzing phosphorylation PASEF data using Fragpipe with PTM prophet. First I converted the .d file to mzML, then search in Fragpipe. But the MSFragger gave exit code 1. I attached the log file from my search. Thank you very much for your support.

Sincerely,
Pei

This is MSconvert setting: 
![image](https://user-images.githubusercontent.com/31378367/112681534-e2d93600-8e3c-11eb-9b40-bacafafb4ef8.png)

[log_2021-03-26_11-44-15.txt](https://github.com/Nesvilab/FragPipe/files/6213866/log_2021-03-26_11-44-15.txt)

**Comment by fcyu** [comment] 2021-03-26 21:24
The log is not complete (there is no error message)

Best,

Fengchao

**Comment by Peilou** [comment] 2021-03-26 21:36
Oh, this is another run with the same error. 
[log_2021-03-26_09-48-27.txt](https://github.com/Nesvilab/FragPipe/files/6214445/log_2021-03-26_09-48-27.txt)

**Comment by fcyu** [comment] 2021-03-27 14:20
Hi Pei,

It is because the size of a single scan is larger than an internal threshold in the spectral loading library. It will be fixed in the next release.

Best,

Fengchao

**Comment by Peilou** [comment] 2021-03-27 15:21
Hi Fengchao,

Thank you for your reply!
I cannot quite understand this. The sample I acquired two weeks ago works
well in MSFragger. Recently I just acquired the same sample with more
injections using the same MS method. Then it gave me this MSFragger error.
Is there any way I can do on my side? I searched the same PASEF .d file, it
worked, but it's phosphorylation samples, I want to use PTM prophet.

Thank you!
Pei

**Comment by fcyu** [comment] 2021-03-27 15:41
Yes, the problem is from parsing the mzML. I guess using .d won't have this error. But PTM-Prophet does not support .d or mgf.

Best,

Fengchao

**Comment by anesvi** [comment] 2021-03-27 15:48
Would be have that problem if MGF was generated using Bruker’s software, and converted to mxML rom mgf?

**Comment by Peilou** [comment] 2021-03-27 15:58
Thank you for all your responses!
Haven't done that, will try it by converting .d to .mgf by bruker's
software and then to mzML by MSConvert.

I am not sure is the problem from the timsControl software. Here are what I
have done:

Sample A acquired two weeks ago by timsTOF pro controlled by otofcontrol
software. The .d file was converted to .mzML by MSConvert, and searched
with MSFragger and PTM-prophet. I didn't have an error.

Now same sample A acquired by timsTOF pro controlled by timsControl
software (using exactly the same MS acquisition setting method as the one
before) . The .d file was converted to .mzML by MSConvert (same setting as
before), and searched with MSFragger and PTM-prophet. I had an error.
(continuous
batch of spectra appeared to be too long to read)

Thanks
Pei

**Comment by fcyu** [comment] 2021-03-27 16:30
> Now same sample A acquired by timsTOF pro controlled by timsControl
software (using exactly the same MS acquisition setting method as the one
before) . The .d file was converted to .mzML by MSConvert (same setting as
before), and searched with MSFragger and PTM-prophet. I had an error.

I don't know the difference between otofcontrol and timsControl, but have you tried the .d file? 

Best,

Fengchao

**Comment by Peilou** [comment] 2021-03-27 16:39
Yes, I have tried the .d file, and it works.

Now same sample A acquired by timsTOF pro controlled by timsControl
software (using exactly the same MS acquisition setting method as the one
before) . The .d file was converted to .mzML by MSConvert (same setting as
before), and searched with MSFragger and PTM-prophet. I had an error.

**Closed** 2021-03-31 22:40 UTC
