### ISSUE TITLE
Python error `raise KeyError(key) from err KeyError: 'irt'`

### ISSUE THREAD

**Issue by RamonDiazPenya1** [Nesvilab/FragPipe#1685] opened 2024-07-21 21:32 UTC
[log_2024-07-21_23-10-30.txt](https://github.com/user-attachments/files/16326120/log_2024-07-21_23-10-30.txt)
 attach the zipped file by drag & drop here.)

Hi all!

I´ve failed to generate a spectral library with DIA files. There is a message at the end of the log indicating:"

Library not generated, not enough peptides could be found for alignment.
2024-07-21 23:10:30 - Info: 0 redundant PSMs identified after filtering with C:\Proteomics\NavarraBiomed\Projects\278-Mirja\DIANNsearch\Fragger-Library\psm.tsv and C:\Proteomics\NavarraBiomed\Projects\278-Mirja\DIANNsearch\Fragger-Library\peptide.tsv
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

Additionally, there are some warnings related to Python. 

Would you mind helping me?

Thanks,

**Comment by fcyu** [comment] 2024-07-21 22:15
Another error due to Python, I think I have seen a similar one before. @guoci can you take a look when you have time?

Thanks,

Fengchao

**Comment by fcyu** [comment] 2024-08-01 18:11
Hi @RamonDiazPenya1 ,

Could you share your raw files and fasta file with us to debug?

Thanks,

Fengchao

**Comment by hahahaL** [comment] 2024-08-02 03:04
```version：fragpipe-v20.0  java：11.0 MSFragger-3.4.jar philosopher_v4.1.1 python:3.9.13 and 3.10 all test```
  
similar issue ,logs as follows
Info: 51894 redundant PSMs identified after filtering with D:\test1\lib\psm.tsv and D:\test1\lib\peptide.tsv
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\easypqp-script.py", line 33, in <module>
    sys.exit(load_entry_point('easypqp==0.1.48', 'console_scripts', 'easypqp')())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1719, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\main.py", line 201, in library
    generate(infiles, outfile, psmtsv, peptidetsv, perform_rt_calibration, rt_referencefile, rt_reference_run_path, rt_filter, perform_im_calibration, im_referencefile, im_reference_run_path, im_filter, psm_fdr_threshold, peptide_fdr_threshold, protein_fdr_threshold, rt_lowess_fraction, rt_psm_fdr_threshold, im_lowess_fraction, im_psm_fdr_threshold, pi0_lambda, peptide_plot_path, protein_plot_path, min_peptides, proteotypic, consensus, nofdr)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\easypqp\library.py", line 448, in generate
    pepida = pepida.loc[np.isfinite(pepida['irt'])]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\frame.py", line 4102, in __getitem__
2024-08-01 15:54:17 - Info: easypqp_rt_alignment_E1; Peptide overlap between run and reference: 0.
2024-08-01 15:54:17 - Info: easypqp_rt_alignment_E1; Skipping run because not enough peptides could be found for alignment.
    indexer = self.columns.get_loc(key)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\indexes\range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'irt'
Library not generated, not enough peptides could be found for alignment.
Library not generated, not enough peptides could be found for alignment.
Please try using other options for alignment (e.g. ciRT if used other options)
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping

**Comment by fcyu** [comment] 2024-08-02 03:07
Hi @hahahaL , could you share your mzML/raw files, fasta, and log files? We need them to reproduce and debug the error.

Thanks,

Fengchao

**Comment by hahahaL** [comment] 2024-08-02 03:25
> Hi @hahahaL , could you share your mzML/raw files, fasta, and log files? We need them to reproduce and debug the error.
> 
> Thanks,
> 
> Fengchao

Quick reply, thanks. The relevant files  I need to confirm if I can share it or not

**Comment by RamonDiazPenya1** [comment] 2024-08-02 11:01
Hi Fengchao!

Here you are the files, you ask for.

https://1drv.ms/f/c/4e637d094b8572e9/EulyhUsJfWMggE7WOAAAAAABlG3vIQovTL1pkRfPp_aaQA?e=RCcBRP

Thanks!

**Comment by fcyu** [comment] 2024-08-02 13:54
Thanks @RamonDiazPenya1 . Could you also upload the fasta file `2024-05-25-decoys-RocSPT_db_240515.fasta.fas`?

Best,

Fengchao

**Comment by fcyu** [comment] 2024-08-02 15:07
Hi @RamonDiazPenya1 ,

Thank you for sharing the files. I was able to reproduce the bug. It was actually due to a bug when using the `psm.tsv` as input. For now, could you switch back to `pepXML`, which is our default option?

![image](https://github.com/user-attachments/assets/9186e304-37de-4784-96f7-df82b4738a40)

@dpolasky , could you take a look at this bug? It seems that when loading from `psm.tsv`, it adds the additional suffix `_rankX` in the `group_id`, which breaks the program. I guess you didn't notice it because it only happens with DIA data.

![image](https://github.com/user-attachments/assets/74c3ba21-ee31-4312-877b-6889dfbf9968)

It also seems that loading from `psm.tsv` is much slower than loading from `pepXML`: 0.80 min vs 2.76 min. Maybe need to optimize.

Best,

Fengchao

**Comment by dpolasky** [comment] 2024-08-05 14:58
@fcyu I've fixed the bug in f4ade11 - it will now correctly get the spectrum rank when converting from psm.tsv, and match what the library command is expecting to find for the group_id. 

Best,
Dan

**Comment by RamonDiazPenya1** [comment] 2024-08-05 15:59
Than you so much!

**Comment by fcyu** [comment] 2024-08-05 16:08
Thanks @dpolasky , the commit looks great! 

Do you want to push the new version 0.1.49 to the upstream and release it?

Best,

Fengchao

**Comment by dpolasky** [comment] 2024-08-06 13:44
Hi @RamonDiazPenya1,
The update is now available - if you uninstall easypqp and reinstall with the new version (0.1.49), the issue should be fixed when converting from psm.tsv files. 

Best,
Dan

**Comment by RamonDiazPenya1** [comment] 2024-08-06 14:35
Fantastic!

**Closed** 2024-08-07 17:32 UTC
Labels: speclib
