### ISSUE TITLE
How to specify IonQuant .jar path in headless mode?

### ISSUE THREAD

**Issue by GregStacey** [Nesvilab/FragPipe#733] opened 2022-06-24 18:27 UTC
I'm attempting to run FragPipe in headless mode on a cluster, and I believe I've successfully followed the steps here https://fragpipe.nesvilab.org/docs/tutorial_headless.html. However unlike the GUI where I see paths for MSFragger, IonQuant, Philosopher and python, I don't see a way to tell headless FragPipe where the IonQuant .jar file is, either in the arguments or the workflow file.

How does headless FragPipe find the IonQuant .jar file? Is it enough to have it in the tools/ folder?

**Comment by fcyu** [comment] 2022-06-24 18:41
This is a good question! I forgot to create a flag for IonQuant's path.

For now, you can either add a `fragpipe-config.bin-ionquant=<path to IonQuant.jar>` entry to the workflow file, or configure the path using the GUI.

Sorry for the oversight. We will fix it soon.

Best,

Fengchao

**Comment by GregStacey** [comment] 2022-06-24 18:43
Thanks for such a fast response! We're totally delighted with fragpipe, and I understand the command line version is in development, so no worries.

I'll apply the quick fix in the workflow file. Thanks again.

**Comment by fcyu** [comment] 2022-06-24 18:56
Thanks. Please feel free to let us know if it works well for you.

I also pushed the fix https://github.com/Nesvilab/FragPipe/commit/1cc65fb741aa1c1839ffc7910aef01c3a7037b2c . It will be available in the next version.

Best,

Fengchao

**Comment by GregStacey** [comment] 2022-06-27 21:40
Adding the line `fragpipe-config.bin-ionquant=<path to IonQuant.jar>` to the workflow file worked for me. Thanks again!

**Comment by Munchic** [comment] 2022-06-28 14:37
Hello! Just to follow up on this. I added this ionquant line before executing FragPipe CLI and also turned it on in the workflow but it doesn't seem to trigger the command. The logs shows that IonQuant has the right path but then it overwrites the parameter `ionquant.run-ionquant=false`. Thank you for your help.

Workflow file and log:
 [log.zip](https://github.com/Nesvilab/FragPipe/files/9002002/log.zip)

**Comment by Munchic** [comment] 2022-06-28 17:29
EDIT: it's working now. Turns out the GUI turns off PeptideProphet when IonQuant is on and I turned them both on.

**Comment by snownaing** [comment] 2022-10-13 22:07
Hi, following up on this. I have specified the path to IonQuant.jar and turn the ionquant on in the workflow, but when running FragPipe, it says that `ionquant.run-ionquant=false`. What's overriding this? Thanks. 
[fragpipe_test_log.zip](https://github.com/Nesvilab/FragPipe/files/9780974/fragpipe_test_log.zip)

**Comment by fcyu** [comment] 2022-10-13 22:46
Because you have `quantitation.run-label-free-quant=false`. It controls if FragPipe perform LFQ. `ionquant.run-ionquant` and `freequant.run-freequant` control which LFQ tool to use: IonQuant or Philosopher. If you want to use IonQuant, you should set  `quantitation.run-label-free-quant=true`, `ionquant.run-ionquant=true` and `freequant.run-freequant=false`.

Best,

Fengchao

**Comment by f-huber** [comment] 2022-11-30 08:22
Hi @fcyu,

I tried using ionquant in fragpipe headless mode (on HPC cluster, within a Singularity container).
I added the line `fragpipe-config.bin-ionquant=<path to IonQuant.jar>` to my workflow and it started running IonQuant. However IonQuant failed because of missing X11 forwarding:

`java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.
        at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
        at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
        at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
        at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/sun.swing.SwingUtilities2.getSystemMnemonicKeyMask(SwingUtilities2.java:2212)
        at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.initComponentDefaults(BasicLookAndFeel.java:1096)
        at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.initComponentDefaults(MetalLookAndFeel.java:440)
        at java.desktop/javax.swing.plaf.basic.BasicLookAndFeel.getDefaults(BasicLookAndFeel.java:150)
        at java.desktop/javax.swing.plaf.metal.MetalLookAndFeel.getDefaults(MetalLookAndFeel.java:1560)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
        at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:629)
        at java.desktop/javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1404)
        at java.desktop/javax.swing.UIManager.initialize(UIManager.java:1517)
        at java.desktop/javax.swing.UIManager.maybeInitialize(UIManager.java:1483)
        at java.desktop/javax.swing.UIManager.getDefaults(UIManager.java:709)
        at java.desktop/javax.swing.UIManager.getColor(UIManager.java:751)
        at org.jfree.chart.JFreeChart.<clinit>(JFreeChart.java:143)
        at org.jfree.chart.ChartFactory.createHistogram(ChartFactory.java:2042)
        at a.a(Unknown Source)
        at t.<init>(Unknown Source)
        at ionquant.IonQuant.main(Unknown Source)
Process 'IonQuant' finished, exit code: 1
Process returned non-zero exit code, stopping
`
I attached the full log for your information.
[fragpipe.log.zip](https://github.com/Nesvilab/FragPipe/files/10120993/fragpipe.log.zip)


Do you know how to solve this issue? Maybe in your next release?

With best regards,

Florian

**Comment by fcyu** [comment] 2022-11-30 20:55
Hi @f-huber ,

Thank you very much for your bug report. 

I think it is due to a rare case that the computer does not have X11 but the `DISPLAY` environment variable is set. Can you try the pre-release version from https://www.dropbox.com/sh/22vh8lmala2l8hs/AAC7lLx8Qk8iF0n2YGAWfOtJa?dl=0 ? You need to use the new versions of all FragPipe, MSFragger, Philosopher, and IonQuant.

Best,

Fengchao

**Comment by f-huber** [comment] 2022-12-01 09:57
Hi @fcyu , 

Thanks for your help. I downloaded the pre-release version for testing, however I get an error when I try running fragpipe (GUI) [I would like to first generate the workflow file, hence I need the GUI).
For information, I get the same error when running fragpipe in local and within a singularity container.
Here is the actual error message:

`2022-12-01 10:53:56,015 ERROR - Something unexpected happened!
java.lang.NullPointerException: null
        at com.dmtavt.fragpipe.tools.ionquant.QuantPanelLabelfree.isEnabled(QuantPanelLabelfree.java:107)
        at java.desktop/javax.swing.border.TitledBorder.getLabel(TitledBorder.java:743)
        at java.desktop/javax.swing.border.TitledBorder.getBorderInsets(TitledBorder.java:385)
        at java.desktop/javax.swing.border.AbstractBorder.getBorderInsets(AbstractBorder.java:75)
        at java.desktop/javax.swing.JComponent.setBorder(JComponent.java:1812)
        at com.dmtavt.fragpipe.tools.ionquant.QuantPanelLabelfree.init(QuantPanelLabelfree.java:181)
        at com.github.chhh.utils.swing.JPanelBase.<init>(JPanelBase.java:34)
        at com.dmtavt.fragpipe.tools.ionquant.QuantPanelLabelfree.<init>(QuantPanelLabelfree.java:65)
        at com.dmtavt.fragpipe.tabs.TabQuantificationLfq.init(TabQuantificationLfq.java:41)
        at com.dmtavt.fragpipe.tabs.TabQuantificationLfq.<init>(TabQuantificationLfq.java:30)
        at com.dmtavt.fragpipe.Fragpipe.createTabs(Fragpipe.java:584)
        at com.dmtavt.fragpipe.Fragpipe.initUi(Fragpipe.java:637)
        at com.dmtavt.fragpipe.Fragpipe.<init>(Fragpipe.java:189)
        at com.dmtavt.fragpipe.Fragpipe.lambda$displayMainWindow$3(Fragpipe.java:453)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by fcyu** [comment] 2022-12-01 14:42
Hi @f-huber ,

I could not reproduce your error. Could you tell me how you started FragPipe GUI?

Thanks,

Fengchao

**Comment by fcyu** [comment] 2022-12-01 17:05
Hi @f-huber ,

Thank you very much for your bug report. I think I found the bug and fixed it. Can you try the version 19.0-build33 in https://www.dropbox.com/sh/22vh8lmala2l8hs/AAC7lLx8Qk8iF0n2YGAWfOtJa?dl=0 ?

Thanks,

Fengchao

**Comment by f-huber** [comment] 2022-12-02 10:19
Hi @fcyu , 
I gave it a try, now fragpipe GUI loads correctly. However, the run failed with the following error message:
`2022-12-02 11:10:44,409 ERROR - Missing assets: /softwares/fragpipe/lib/../tools/diann/1.8.2_beta_8/linux/diann-1.8.1
`
I had a look, and indeed, the fragpipe/tools/diann/1.8.2_beta_8/linux/ folder is empty.

In addition, there are a few warnings related to the softwares as you can see in the attached print screen image. It has to do with philosopher (I used the "philosopher-v4.5.1-RC25" file from the dropbox package) and also a warning about python.

![517835BD-4C1F-4E61-AE2C-2B0395AB7A98](https://user-images.githubusercontent.com/93529444/205270071-6d0d6cad-59c4-40c0-884f-2ef7c149cd36.jpeg)

I hope this helps.

Florian

**Comment by fcyu** [comment] 2022-12-02 14:25
Hi Florian,

Yes, you are right. build 33 does not have the Linux version of DIA-NN. Please find the build 36 in the same Dropbox link.

As to those two warnings, can you confirm that `/software/philosopher/philosopher` is not a Philosopher executable file? For the python warning, I think it is from the previous session. You can closing that warning.

Best,

Fengchao

**Closed** 2022-12-03 18:01 UTC
Labels: FragPipe

**Comment by f-huber** [comment] 2022-12-05 12:57
Hi @fcyu,

**Comment by fcyu** [comment] 2022-12-05 17:04
Hi @f-huber ,

As IonQuant complained, "there are empty entries in the Protein column of /data/fhuber3/rBCG_TB_MS/MS_ANALYSIS/FRAGPIPE/BCG/TEST/ET4_THP1_rBCG24hr_I_R1_1/psm.tsv". Your psm.tsv file also confirms this error:

![image](https://user-images.githubusercontent.com/6926299/205697653-18f47514-2742-4288-9e9e-82b359afddec.png)

For now, I don't know the source of this bug. Could you please create a new issue (because it it no longer related to "How to specify IonQuant .jar path in headless mode?") and share us your `interact-20160621_BCG_24hr_R1.pep.xml` file?

Thanks,

Fengchao

**Comment by f-huber** [comment] 2022-12-06 09:55
Hin @fcyu,
Thanks for your help. You're right, I create a new issue and add the files needed.
Florian
