### ISSUE TITLE
Number of the raw scans

### ISSUE THREAD

**Issue by fazeliniah** [Nesvilab/FragPipe#848] opened 2022-10-05 14:31 UTC
Dear FragPipe developer team, 
For our large scale bottom-up proteomics project, we are interested to know what percentage of ms/msms raw spectra were assigned to peptides.  Is there an easy way to do this from the output files?
Thank you!

**Comment by dpolasky** [comment] 2022-10-05 15:51
Hi @fazeliniah,
It isn't calculated automatically anywhere, but all the info you'd need is in the log file. The number of MS2 scans in each raw file is printed by both the initial raw file check (output looks like: `rawname.mzML: Scans = 27658`) and MSFragger (e.g. `rawname.mzML 2.9 s
		[progress: **27658/27658** (100%) - 12397 spectra/s] 2.2s | postprocessing 0.3 s`) and the filter command will say the number of PSMs (also the same as the number of rows in the psm.tsv table). 

Best,
Dan

**Comment by fcyu** [comment] 2022-10-05 16:43
It is a duplicate of https://github.com/Nesvilab/FragPipe/issues/676, https://github.com/Nesvilab/FragPipe/issues/200

**Closed by fcyu** 2022-10-05 16:43 UTC
