### ISSUE TITLE
DIAUMPIRE DirectoryNotEmpty error (Process 'UmpireSe' finished, exit code: 1)

### ISSUE THREAD

**Issue by ekvall93** [Nesvilab/FragPipe#314] opened 2021-03-04 11:13 UTC
Ubuntu 18.04.5 LTS
FragPipe v.14.0

Hi, I'm using Fragpipe and I get a "DirectoryNotEmpty" error after UmpireSe has processed the XML file and copying the results over to the working directory.

Here's the error log:

https://firebasestorage.googleapis.com/v0/b/terran3-f2341.appspot.com/o/fragpipe%2Flog_2021-03-04_12-03-17.txt?alt=media&token=dfce5362-deaf-4921-b284-76c3e4ddfecd

Thanks for any help.

Best regards,

Markus Ekvall

**Comment by anesvi** [comment] 2021-03-04 16:34
We are about to release a version of FragPipe with improved DIA-Umpire support
Perhaps we can give you that version to test?

Fengchao, can you send?

**Comment by ekvall93** [comment] 2021-03-04 16:44
@anesvi yes, that would be great. Thank you!

**Comment by fcyu** [comment] 2021-03-04 16:49
Hi Markus,

Sounds great! Please find the pre-release version from [https://umich.box.com/s/ruzidu7uz277r5r4fnihs08e9avghpme](https://umich.box.com/s/ruzidu7uz277r5r4fnihs08e9avghpme)

Best,

Fengchao

**Comment by ekvall93** [comment] 2021-03-04 16:53
Hi @fcyu,

Thank you. I will let you know id the problem persists.

Best regards,

Markus Ekvall

**Comment by ekvall93** [comment] 2021-03-04 18:33
The version seems very nice! I especially like the graph.

Unfortunately, the problem persists. It might be me that do something wrong. The error comes from when using FileMove to move the *_PEAK directory to the working directory i.e.,

java -cp /home/ekvall/Desktop/fragpipe/lib/fragpipe-14.0.jar com.github.chhh.utils.FileMove 
/sdd/proteomics/DATA/PXD014076/Symb/mzXML/Symb_Proteome_DIA_RAW_S01_Peak /home/ekvall/Desktop/sample_with_styDaXML/Symb_Proteome_DIA_RAW_S01_Peak

It's exactly the same error that I sent in the old error log:

https://firebasestorage.googleapis.com/v0/b/terran3-f2341.appspot.com/o/fragpipe%2Flog_2021-03-04_12-03-17.txt?alt=media&token=dfce5362-deaf-4921-b284-76c3e4ddfecd

Best regards,

Markus

**Comment by guoci** [comment] 2021-03-04 20:56
@ekvall93 try deleting the directory `home/ekvall/Desktop/sample_with_styDaXML/Symb_Proteome_DIA_RAW_S01_Peak` and restart.

**Comment by guoci** [comment] 2021-03-04 21:51
@ekvall93 for a temporary fix, try setting the working directory and the input files directory to be on the same drive.
The problem is that `/sdd/proteomics/DATA/PXD014076/Symb/mzXML/Symb_Proteome_DIA_RAW_S01_Peak` and `/home/ekvall/Desktop/sample_with_styDaXML/Symb_Proteome_DIA_RAW_S01_Peak` are on different drives.
I will try to fix this in FragPipe on the next release.

**Comment by ekvall93** [comment] 2021-03-04 23:39
@guoci It worked! Thank you so much.

**Comment by guoci** [comment] 2021-03-05 19:55
resolved in ff21ffb. Closing

**Closed by guoci** 2021-03-05 19:55 UTC
Labels: DIA-U

**Comment by guoci** [comment] 2021-03-09 20:34
tested at 666adb7c1ca162e319e7f041eac86c0aff8fc057, closing
