### ISSUE TITLE
How to visualise DIA-NN predicted spectra

### ISSUE THREAD

**Issue by lbwfff** [Nesvilab/FragPipe#1435] opened 2024-02-06 07:05 UTC
- Describe the issue or question:

Hi, I want to show experimental and DIA-NN predicted spectra like this in MSBooster manuscript![Screenshot 2024-02-06 at 8 49 04 AM](https://github.com/Nesvilab/FragPipe/assets/74947198/59e23438-9500-4393-beae-58af4c453ca3), I know how to get experimental spectra but how should I get DIA-NN predicted spectra.

Thanks
LeeLee

**Comment by fcyu** [comment] 2024-02-06 14:29
Hi LeeLee,

Yes, you should be able to visualize the predicted spectra if you enabled MSBooster when running the job. 

If you could not, @KaiLiCn , can you take a look?

Best,

Fengchao

**Comment by KaiLiCn** [comment] 2024-02-06 14:59
Hi LeeLee,

If you enabled MSBooster when you ran your job, you could click `Tools` and then click `Show Predicted` on the spectrum panel. 
![image](https://github.com/Nesvilab/FragPipe/assets/29800230/1b164796-94ee-4fda-84fa-3120033fe826)

Let me know if you have any issues to import predicted spectra.

Kai

**Comment by lbwfff** [comment] 2024-02-07 10:54
Hi kai,

thanks for your reply I found the Show Predicted panel. but I'm having some other problems, it seems that after clicking Show Predicted the PDV is still returning me the experimental spectra, and I'm sure I'm running MSBooster, what should I do to fix this situation?

![Screenshot 2024-02-07 at 2 45 49 PM](https://github.com/Nesvilab/FragPipe/assets/74947198/802b1e18-a667-4199-a050-f1b89fec3d60)
![Screenshot 2024-02-07 at 2 46 08 PM](https://github.com/Nesvilab/FragPipe/assets/74947198/b696e5c3-fb84-4016-bacb-251c2f4fde55)

Thanks,
LeeLee

**Comment by lbwfff** [comment] 2024-02-08 06:28
Hi Kai,

I uploaded the whole result folder, but I didn't upload the raw files considering the file size, the raw file was downloaded from MSV000091887 and converted to mzML format using msconvert.

```
for f in $(find ./ -name '*.raw');
do
	f2=${f/.raw/.mzML}
	if [ ! -f $f2 ];
	then
		echo $f2
		docker run --rm -e WINEDEBUG=-all -v /data/ADMS/:/data chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64 wine msconvert --64 --zlib --filter "peakPicking" --filter "zeroSamples removeExtra 1-"  /data/$f
	fi
done
```

**Comment by yangkl96** [comment] 2024-02-08 21:15
Hi LeeLee,

It seems that the DIA-NN predicted library you provided `spectraRT.predicted.bin` is truncated and smaller than the actual number of peptide candidates that are listed in `spectraRT_full.tsv`. Could you go to the command line and run the following:
`/scratch/lb4489/fragpipe/fragpipe/tools/diann/1.8.2_beta_8/linux/diann-1.8.1.8 --lib /scratch/lb4489/project/MS_data/lbf_mzML/fragpipe/18NIH_M_812_032223/spectraRT.tsv --predict --threads 25 --strip-unknown-mods --predict-n-frag 100`
This should recreate the predicted library `spectraRT.predicted.bin`,  hopefully to the full size and larger than your old file. You can then go back to FragPipe-PDV and visualize the spectra.

Let us know if that fixes your issue,
Kevin

**Comment by lbwfff** [comment] 2024-02-09 06:09
Hi Kevin, thanks for your reply, this method worked for me!

**Comment by yangkl96** [comment] 2024-02-09 16:06
That's great to hear! I'll close this issue, but please let us know if we can help you in any other way.

**Closed by yangkl96** 2024-02-09 16:06 UTC
Labels: FragPipe-PDV

**Comment by MartaEspinosa** [comment] 2026-03-23 08:41
Dear developers,

I am facing a similar issue here. I have my results, and I am trying to compare some experimental spectra with its predicted in a mirror plot, like the previous user, but I keep getting an error:

> Cannot read field "mzs" because "tmp" is null

I am trying with FragPipe 23.1 and 24 and I get the same issue. I am pretty sure I have MSBooster enabled and, for what I understand in the log file, the predictions are being done. I also tried with what you suggested to the previous user, to make sure the predicted library was ok, but still the same error.

Could you please help me? I uploaded the log file. Please let me know which other information you may need.

Thank you so much,

Best,

Marta

[PublicSearch_v24.FDR3.log](https://github.com/user-attachments/files/26177074/PublicSearch_v24.FDR3.log)

**Comment by fcyu** [comment] 2026-03-23 13:56
@MartaEspinosa could you share the screenshot with the error?

Thanks,

Fengchao

**Comment by MartaEspinosa** [comment] 2026-03-23 14:58
Hi Fengchao,

of course. 

<img width="382" height="192" alt="Image" src="https://github.com/user-attachments/assets/933a39bc-2182-444b-844a-db5a54a4db15" />

Thanks

**Comment by fcyu** [comment] 2026-03-23 15:02
@KaiLiCn , can you take a look?

Thanks,

Fengchao

**Comment by MartaEspinosa** [comment] 2026-03-30 07:27
Hi @KaiLiCn ,

Any idea on how I could solve this issue?

Thanks so much in advance,

Marta

**Comment by KaiLiCn** [comment] 2026-03-30 15:08
Hi Marta,

Sorry for the late response. It seems like there is an issue in your predicted spectrum file. Could you share your result folder and raw file with us? We can take a look.

Best,
Kai

**Comment by MartaEspinosa** [comment] 2026-03-31 09:25
Hi Kai,

I share a link with the result folder, the analysis is done with a lot of sample, so I am afraid I will not be able to share the raw files (they are all public data but many files were analyzed here)

[https://www.swisstransfer.com/d/1a42830d-3776-45d8-9d6e-07c4f1f536c1]

here is the link with the output folder. Let me know if you can work with that

Thanks!

**Comment by KaiLiCn** [comment] 2026-04-01 15:16
Hi Marta,

I download your result and tested it using one raw file (201703011_QEh1_LC2_FaMaChCh_SA_HLApI_3865-DM_1_R1.raw). I didn't see the error. Could you give me more details? Did you see the issue across all PSMs, or any specific modified PSM? Maybe some PSMs in specific raw files?

Kai

**Comment by MartaEspinosa** [comment] 2026-04-01 15:39
Hi Kai, 

Thanks for trying to reproduce it.

I still observe the same, with all the PSMs I try. It is true, though, that I checked now with another result folder much smaller (of another analysis of other data) and I do not have the same problem. Which is great and means my version and installation are correct.

Here I always get the same error, the above one "Cannot read field "mzs" because "tmp" is null". 
For example, I peptide I would like to look at, ALYTRLPASK, in the same raw file you checked. 
They way I do it is just opening PDV from FragPipe, which reads the psm.tsv that is the results folder I sent you, nothing else...

This search was done with many raw files, is that information contained in the predicted spectrum file? May it has something to do?

Thanks again

**Comment by KaiLiCn** [comment] 2026-04-01 15:55
Hi Marta,

Thank you for your information. I can replicate your error now. I will fix it soon.

Kai

**Comment by KaiLiCn** [comment] 2026-04-06 21:12
Hi Marta,

We fixed this issue. You have to replace two packages in FragPipe manually. 

1. Replace batmass-io-1.36.5.jar in `tools `folder with this one: https://www.dropbox.com/t/EJFXZAY3vfP5CqK1
2. Replace FP-PDV-1.5.8.jar in `tools\FP-PDV` folder with this one: https://www.dropbox.com/t/aQqgsVIgjU0g7XsV

Don't forget delete the old version of packages.

Best,
Kai

**Comment by MartaEspinosa** [comment] 2026-04-07 09:36
Hi Kai,

It works perfectly! I tried with several peptides and it works for all the ones I tried.

Thanks a lot for the efficiency and, of course, the help.

Have a great day.

Best,
Marta
