### ISSUE TITLE
MSFragger got the `what(): locale::facet::_S_create_c_locale name not valid` error when SSH a Linux from Mac

### ISSUE THREAD

**Issue by ClaSofMag** [Nesvilab/FragPipe#1171] opened 2023-07-03 10:07 UTC
Hello,

I was trying to run fragpipe on linux and got this error at the end of my log:
MSFragger [Work dir: /home/claudia/fragpipe_output/results]
java -jar -Dfile.encoding=UTF-8 -Xmx25G /home/claudia/old/fragpipe/tools/MSFragger-3.8/MSFragger-3.8.jar /home/claudia/fragpipe_output/results/fragger.params mzML/P_T6_P3.mzML mzML/P_T7_P3.mzML mzML/P_T7_P5.mzML mzML/P_T4_P3.mzML mzML/P_T4_P5.mzML mzML/P_T6_P1.mzML mzML/P_T2_P1.mzML mzML/P_T2_P3.mzML mzML/P_T5_P1.mzML mzML/P_T5_P3.mzML mzML/P_T9_P3.mzML mzML/P_T9_P4.mzML mzML/P_T1_P2.mzML mzML/P_T1_P5.mzML mzML/P_T3_P3.mzML mzML/P_T3_P6.mzML mzML/P_T8_P1.mzML mzML/P_T8_P5.mzML
MSFragger version MSFragger-3.8
Batmass-IO version 1.28.12
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Process 'MSFragger' finished, exit code: 134
Process returned non-zero exit code, stopping

Cancelling 169 remaining tasks

Here is the log
[fragpipe_plasma.5192.txt](https://github.com/Nesvilab/FragPipe/files/11935635/fragpipe_plasma.5192.txt)

Thank you for your support

**Comment by fcyu** [comment] 2023-07-03 11:39
It seems that something was wrong with the `locale` in your Linux. Could you run `locale` command and send us the screenshot of the printed message?

Best,

Fengchao

**Comment by ClaSofMag** [comment] 2023-07-03 14:29
here it is

[claudia@ceta ~]$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.utf-8
LC_CTYPE=UTF-8
LC_NUMERIC="en_GB.utf-8"
LC_TIME="en_GB.utf-8"
LC_COLLATE="en_GB.utf-8"
LC_MONETARY="en_GB.utf-8"
LC_MESSAGES="en_GB.utf-8"
LC_PAPER="en_GB.utf-8"
LC_NAME="en_GB.utf-8"
LC_ADDRESS="en_GB.utf-8"
LC_TELEPHONE="en_GB.utf-8"
LC_MEASUREMENT="en_GB.utf-8"
LC_IDENTIFICATION="en_GB.utf-8"
LC_ALL=

**Comment by fcyu** [comment] 2023-07-03 14:32
> locale: Cannot set LC_CTYPE to default locale: No such file or directory
> locale: Cannot set LC_ALL to default locale: No such file or directory
> LC_ALL=

I guess these are the cause. Could you troubleshoot your Linux configuration with your IT department?

Best,

Fengchao

**Comment by ClaSofMag** [comment] 2023-07-03 16:40
Ok I think we found the problem. I'll explain in case it is useful for anyone. 
Apparently, when you login over ssh from a Mac to a linux, your terminal automatically sets environment variables. So, if you're connecting from MacOS using Terminal, go to Terminal Settings>Advanced and uncheck "Set locale environment variables at startup".

It is not working perfectly!

Thank you for your support

**Comment by fcyu** [comment] 2023-07-03 16:43
Thank you very much for the troubleshooting and feedback. The information will definitely help others.

I will close this issue since it has been addressed.

Best,

Fengchao

**Closed by fcyu** 2023-07-03 16:43 UTC
