### ISSUE TITLE
SpecLib Generation Issue

### ISSUE THREAD

**Issue by azying312** [Nesvilab/FragPipe#1647] opened 2024-06-25 16:38 UTC
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
[log_2024-06-24_18-10-22.txt](https://github.com/user-attachments/files/15974301/log_2024-06-24_18-10-22.txt)

**- Describe the issue or question:**
I am getting a value error, "not enough values to unpack (expected 3, got 2)" as well as an error with not enough peptides found for alignment. I attached my log file, but I was wondering if there was any ideas on what I am doing wrong? I loaded the default workflow with some edits and changed the RT calibration to biognosys_iRT.

Another unrelated issue is that when I tried to run with PeptideProphet instead of Percolator for PSM Validation, I noticed that in PeptideProphet, it says "MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN". I was confused by this since we used a ThermoFisher Orbitrap Eclipse Tribrid Mass Spectrometer for acquiring the data. I attached the log file for that run as well.
[log_2024-06-24_13-48-56.txt](https://github.com/user-attachments/files/15974623/log_2024-06-24_13-48-56.txt)

**Comment by fcyu** [comment] 2024-06-25 19:33
> I am getting a value error, "not enough values to unpack (expected 3, got 2)" as well as an error with not enough peptides found for alignment. I attached my log file, but I was wondering if there was any ideas on what I am doing wrong? I loaded the default workflow with some edits and changed the RT calibration to biognosys_iRT.

The reason may be those "edits". Basically, the "PTMs" tab was enabled by mistake. Could you load the workflow and do not change any parameters unless necessary?

> Another unrelated issue is that when I tried to run with PeptideProphet instead of Percolator for PSM Validation, I noticed that in PeptideProphet, it says "MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN". I was confused by this since we used a ThermoFisher Orbitrap Eclipse Tribrid Mass Spectrometer for acquiring the data. I attached the log file for that run as well.

They are fine. Those are neither error nor warning. And they won't affect the result.

Best,

Fengchao

**Comment by azying312** [comment] 2024-06-25 19:41
Hi Fengchao,

Thanks for this, I am doing a PTM workflow, but it's closed search for peptide identification. I might have misunderstood the purpose of PTM-Shepherd since it seems like it's for open search only. I am currently re-running the process without it, but we added the iRT from Biognosys into the samples so I will keep that on the spectral library generation. I will follow-up if there's any further issue.

Thank you,
Alice

**Comment by azying312** [comment] 2024-06-25 22:49
Hi,

I reran the analysis without PTM-shepherd and with the default workflow besides the biognosys iRT for spectral library generation. I am still getting the same value error: "not enough values to unpack (expected 3, got 2)". I attached the new log file, could you please see what I am doing wrong here? 
[log_2024-06-25_15-27-25.txt](https://github.com/user-attachments/files/15980120/log_2024-06-25_15-27-25.txt)


Best,
Alice

**Comment by fcyu** [comment] 2024-06-25 22:51
I have no idea now. @guoci , can you take a look?

Thanks,

Fengchao

**Comment by dpolasky** [comment] 2024-06-26 14:17
Looks like this was a bug from my changes - I've pushed a fix to our nesvilab easypqp repository. @fcyu can you push it to the main easypqp when you have a chance?

Alice, you can get the fixed version from our easypqp fork by updating it to version 0.1.46 using the commands:
```
pip uninstall easypqp
pip install git+https://github.com/nesvilab/easypqp.git
```

Best,
Dan

**Comment by fcyu** [comment] 2024-06-26 14:27
Sure. Have pushed the commit and released the version 0.1.46.

Best,

Fengchao

**Comment by azying312** [comment] 2024-06-26 16:22
Hi Dan and Fengchao,

I really appreciate all the help. I am rerunning the pipeline now and will follow-up if there's a further problem.

Best,
Alice

**Comment by azying312** [comment] 2024-06-26 21:26
Hi again,

I reran the analysis and there is still a problem for me with the spectral library module. It seems to be something new since I don't have the unpacking error anymore. Instead, I have:
PermissionError: [WinError 5] Access is denied
Process 'SpecLibGen' finished, exit code: 1
Process returned non-zero exit code, stopping
[log_2024-06-26_14-09-28.txt](https://github.com/user-attachments/files/15995975/log_2024-06-26_14-09-28.txt)

Is this a permission error on my side? It seems FragPipe was able to access all the raw data files for the other modules though. Again, I really appreciate the help!

Best,
Alice

**Comment by azying312** [comment] 2024-06-27 00:45
Just as a follow-up but I did run it without the SpecLib module and it works perfectly fine. I would like to create a spectral library from FragPipe if possible though.

[log_2024-06-26_17-29-05.txt](https://github.com/user-attachments/files/16006318/log_2024-06-26_17-29-05.txt)

**Comment by fcyu** [comment] 2024-06-27 00:48
@guoci @dpolasky , any idea about the new Python error?

Thanks,

Fengchao

**Comment by dpolasky** [comment] 2024-06-27 13:32
Hi Alice,
It's giving a permission denied error when trying to call the easypqp python module, which is weird - might be something wrong with the installation or the path. Can you try uninstalling and reinstalling easypqp again? If it gives the same error, can you try running the command `C:\Users\jbons\AppData\Local\Programs\Python\Python39\Scripts\easypqp.exe --version` and seeing if it works from the terminal? 

Best,
Dan

**Comment by azying312** [comment] 2024-06-27 21:42
Hi Dan,

Thanks that fixed that issue, it seems like there is still some error in spectral library generation for me. The samples were spiked with iRT from biognosys (and I selected that in the module), but I am getting there are "not enough peptides could be found for alignment." 
[log_2024-06-27_12-23-47.txt](https://github.com/user-attachments/files/16021541/log_2024-06-27_12-23-47.txt)
I have been able to generate spectral libraries with other softwares so I was wondering if you had some idea as to what might be going wrong here?

Best,
Alice

**Comment by dpolasky** [comment] 2024-06-28 20:45
Hi Alice,
Glad the conversion is working now at least. It looks like there is an error coming from the internal data structures, but I'm not sure the reason for it. Do you see the file \\bigrock\GibsonLab\users\Joanna\For_Alice\Spectral_Libraries\FragPipe\067_editedMSfragger_default_biognosys_AZ\irt.tsv, and if so, does its content look normal? If that looks fine I may need to debug more on our end. 

Best,
Dan

**Comment by azying312** [comment] 2024-06-28 21:25
Hi Dan,

Yes, that is great. The irt.tsv file seems normal to me, it's not exactly the same, but decently close. I have attached the irt.tsv (as a pdf) as well as the Biognosys iRT kit reference (sheet 3) for your review as well. 

[irt-kit-reference-sheet.xlsx](https://github.com/user-attachments/files/16036920/irt-kit-reference-
[irt.pdf](https://github.com/user-attachments/files/16036923/irt.pdf)
sheet.xlsx)

Best,
Alice

**Comment by azying312** [comment] 2024-06-28 21:38
On a similar note, I have been testing skipping the spectral library generation to see the skyline document. I have tried with both MSBooster and Percolator (default workflow) as well as PeptideProphet for the PSM validation, but have gotten error with there being no peptides.

[log_2024-06-27_18-32-54.txt](https://github.com/user-attachments/files/16036981/log_2024-06-27_18-32-54.txt)
[log_2024-06-28_12-21-59.txt](https://github.com/user-attachments/files/16036982/log_2024-06-28_12-21-59.txt)

It did work once in generating a Skyline document, but only had 4 proteins and 5 peptides, which is not the case.
[log_2024-06-26_17-29-05.txt](https://github.com/user-attachments/files/16006318/log_2024-06-26_17-29-05.txt)

Best,
Alice

**Comment by fcyu** [comment] 2024-06-28 21:52
Hi @azying312 ,

Regarding the Skyline error, could you create a new issue with the files to reproduce the error: https://github.com/Nesvilab/FragPipe/issues. 

We might need to reproduce to figure out the cause.

Thanks,

Fengchao

**Comment by azying312** [comment] 2024-06-28 21:59
Hi Fengchao,

Sounds good, thank you!

Best,
Alice

**Comment by fcyu** [comment] 2024-07-02 18:27
Any idea about this Python error @guoci @dpolasky ?

Thanks,

Fengchao

**Comment by dpolasky** [comment] 2024-07-02 19:35
Still looking into it - need to run some tests.

Best,
Dan

**Comment by azying312** [comment] 2024-07-03 20:01
Hi Dan,

I added the iRT to the fasta file. I sent the fasta file on dropbox to Fengchao. I think the spectral library generation worked, I attached the log file for you to review. The DIA-NN module seems to have run despite not being queued which has not happened before, so I was wondering if I had done something incorrectly? Please let me know if you would want any additional files, I have the new raw data, fasta files, and results folder on the dropbox from Issue #1654.

[log_2024-07-03_12-47-08.txt](https://github.com/user-attachments/files/16090252/log_2024-07-03_12-47-08.txt)

Best,
Alice

**Comment by fcyu** [comment] 2024-07-03 20:05
To be clear, the DIA-NN module did not run, and you let Skyline to take the interact-*.pxp.xml not the spectral library generated by FragPipe as input.

Best,

Fengchao

**Closed** 2024-07-03 21:09 UTC
Labels: speclib

**Comment by a-indra** [comment] 2026-03-19 01:50
Hi all,
When incorporating the iRT peptides into the FASTA, is it fine to paste directly as provided from [Biognosys](https://biognosys.com/resources/irt-kit-further-user-resources/)?

```
>Biognosys|iRT-Kit_WR_fusion
LGGNEQVTRYILAGVENSKGTFIIDPGGVIRGTFIIDPAAVIRGAGSSEPVTGLDAKTPVISGGPYEYRVEATFGVDESNAKTPVITGAPYEYRDGLDAASYYAPVRADVTPADFSEWSKLFLQFGAQGSPFLK
```

Or do they need to be formatted in some other way?

Thanks

**Comment by fcyu** [comment] 2026-03-19 01:52
Better to reformat the header to be the UniProt format

```
>sp|Biognosys|iRT-Kit_WR_fusion Biognosys iRT-Kit_WR_fusion
LGGNEQVTRYILAGVENSKGTFIIDPGGVIRGTFIIDPAAVIRGAGSSEPVTGLDAKTPVISGGPYEYRVEATFGVDESNAKTPVITGAPYEYRDGLDAASYYAPVRADVTPADFSEWSKLFLQFGAQGSPFLK
```
