### ISSUE TITLE
Ability to upload files to PRIDE DB as a complete submission (MzidentML output)

### ISSUE THREAD

**Issue by SC0O8Y** [Nesvilab/FragPipe#660] opened 2022-04-24 11:51 UTC
I was thinking that I would be able to import the results into IDpicker and export them as a MzidentML. I spoke to David T but he said it wasn't implemented, yet i found mention of it in a command line document. (I will try and confirm it isnt possible). 

If anyone knows of a way to get around this Id appreciate it. Otherwise i guess a MassIVE submission alongside the manuscript will have to do. 

Kind regards 

Joel

**Comment by fcyu** [comment] 2022-04-24 14:25
You can try idconvert from ProteoWizard. I used it two years ago, and it worked OK at that time.

Close this issue because it is a duplicate of https://github.com/Nesvilab/FragPipe/issues/265

Best,

Fengchao

**Closed by fcyu** 2022-04-24 14:25 UTC
Labels: enhancement

**Comment by LL1982** [comment] 2024-06-13 17:44
Hi Fengchao,

Do you know any other software instead of idconvert? ProteoWizard does not have Idconvert any more. Thx

Best,

Tao

**Comment by fcyu** [comment] 2024-06-13 17:47
As far as I know, no.

On a side note, I think PRIDE should support the common software's output not the other way around, if they really want people to do a complete submission.

Best,

Fengchao

**Comment by LL1982** [comment] 2024-06-13 17:50
Thank you for your quick reply
